"""integration-brasileirao: adota uma release do cain como final_wheel desta missão (depois do ciclo 4, a rc11).

  python adopt_release.py check <predictor-qualification> <wheel> <wheel sha256> <regenerado.json> <pin> <out.json>
      confere: sha256 da wheel publicada; o brasileirao.json da wheel pina FROZEN_PARAMETERS.json no <pin> com o sha256
      do arquivo nesse commit, e esse arquivo é o de hoje (nada mudou depois do pin); o brasileirao.json da wheel é, byte
      a byte, o que o tools/build_domain_config.py do commit da release gera a partir do <pin> (<regenerado.json>);
      3 sealed_scopes (R16); QUAL-SOAK-001..024 proponíveis com o tipo único; sem proposal_overlays nem result_metrics
      (chaves opcionais que o Brasileirão não declara);
  python adopt_release.py record <qualification/integration-brasileirao> <cain|transport> <tag> <commit> <wheel url>
      <wheel sha256> <nota>
      grava o bloco do pacote em runtime_targets.json (só esse bloco muda).
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

M = "qualification/integration-brasileirao"
SOAK = [f"brasileirao:QUAL-SOAK-{n:03d}" for n in range(1, 25)]


def sha(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def check(root: Path, wheel: Path, wheel_sha: str, regenerated: Path, pin: str, out: Path) -> int:
    checks = []

    def ok(name, cond, **detail):
        checks.append({"check": name, "ok": bool(cond), **detail})

    raw_wheel = wheel.read_bytes()
    ok("wheel sha256 == published release asset", sha(raw_wheel) == wheel_sha, sha256=sha(raw_wheel))
    with zipfile.ZipFile(wheel) as z:
        wheel_config = z.read("cain/orchestration/data/brasileirao.json")
    config = json.loads(wheel_config)
    pinned = subprocess.run(["git", "-C", str(root), "show", f"{pin}:{M}/FROZEN_PARAMETERS.json"],
                            capture_output=True, check=True).stdout
    current = (root / M / "FROZEN_PARAMETERS.json").read_bytes()
    fp = config["frozen_parameters"]
    ok("brasileirao.json pins FROZEN_PARAMETERS at the pin commit with that file's sha256",
       fp["commit"] == pin and fp["sha256"] == sha(pinned) and fp["path"] == f"{M}/FROZEN_PARAMETERS.json",
       frozen_parameters=fp)
    ok("FROZEN_PARAMETERS.json unchanged since the pin", current == pinned, current=sha(current), pinned=sha(pinned))
    ok("brasileirao.json in the wheel == regenerated by the release's tools/build_domain_config.py from the pin (bytes)",
       wheel_config == regenerated.read_bytes(), wheel_sha256=sha(wheel_config),
       regenerated_sha256=sha(regenerated.read_bytes()))
    ok("3 sealed_scopes (R16 holdout)", len(config.get("sealed_scopes", [])) == 3)
    ok("QUAL-SOAK-001..024 proposable with the single allowed type",
       set(SOAK) <= set(config["proposable_hypotheses"])
       and {config["proposable_request_types"][h] for h in SOAK} == set(config["allowed_request_types"]))
    ok("no proposal_overlays and no result_metrics (optional keys the Brasileirão does not declare)",
       "proposal_overlays" not in config and "result_metrics" not in config)
    doc = {"schema": "integration-brasileirao/RELEASE_CHECK/1", "wheel": wheel.name, "pin": pin, "checks": checks,
           "passed": sum(c["ok"] for c in checks), "failed": sum(not c["ok"] for c in checks)}
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(doc, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({k: doc[k] for k in ("passed", "failed")}))
    for c in checks:
        if not c["ok"]:
            print("FAILED", json.dumps(c, ensure_ascii=False))
    return 0 if doc["failed"] == 0 else 1


REPOS = {"cain": "leonardosovienski/cain", "transport": "leonardosovienski/ecosystem-predictor"}


def record(q: Path, key: str, tag: str, commit: str, url: str, wheel_sha: str, note: str) -> int:
    """Replace the block of ``key`` (cain or transport) in runtime_targets.json; the other blocks keep their bytes."""
    path = q / "runtime_targets.json"
    text = path.read_text(encoding="utf-8")
    block = re.search(rf' "{key}": \{{.*?\}},\n', text, re.S)
    assert block and text.count(f' "{key}": {{') == 1
    version = tag.rsplit("-v", 1)[-1].removeprefix("v")
    pad = " " * (len(key) + 5)
    new = (f' "{key}": {{"repo": "{REPOS[key]}", "version": "{version}", "tag": "{tag}",\n'
           f'{pad}"commit": "{commit}",\n'
           f'{pad}"url": "{url}",\n'
           f'{pad}"sha256": "{wheel_sha}",\n'
           f'{pad}"note": {json.dumps(note, ensure_ascii=False)}}},\n')
    path.write_text(text[:block.start()] + new + text[block.end():], encoding="utf-8")
    json.loads(path.read_text(encoding="utf-8"))
    print(f"runtime_targets.json {key} ->", tag, commit[:12])
    return 0


if __name__ == "__main__":
    mode = sys.argv[1]
    if mode == "check":
        raise SystemExit(check(Path(sys.argv[2]), Path(sys.argv[3]), sys.argv[4], Path(sys.argv[5]), sys.argv[6],
                               Path(sys.argv[7])))
    raise SystemExit(record(Path(sys.argv[2]), *sys.argv[3:9]))
