"""integration-brasileirao, contract-revalidation, parte (d) de C24.3 (DOMAIN_CONTRACTS_PRESERVED), no runtime suportado.

Adaptado de qualification/integration-stocks/scripts/contract_d.py. O vetor congelado da Etapa A do Brasileirão
(tests/conformance/fixtures.py do final_commit: request("brasileirao:REQ-E2E-RUNTIME-001"), cujo hash canônico sem
client_ref está conferido contra o resultado da Etapa A em integration-crypto/fixtures/v2/FIXTURES_MANIFEST.json →
brasileirao.request_content_hash_verified) é embrulhado numa ResearchTaskV2 (protocolo congelado, venv do CAIN) e
entregue pelo consumidor do transporte ao adapter, num ambiente de operador de conformidade montado pela própria fixture
(tests/conformance/harness.standard_lab: dataset sintético, a mesma fronteira do operador da Etapa A; nenhum dado real).
Confere:
  * o pedido que o adapter gera tem o mesmo hash canônico sem client_ref do vetor da Etapa A (o request_content_hash que
    o domínio grava no resultado == o sha256 canônico do vetor == o hash conferido da Etapa A);
  * o client_ref volta igual (outcome e resultado V2);
  * o payload de domínio no ResultV2 é byte-idêntico ao do adapter_api (== `brasileirao-research show`, processo novo).
Uso (com o env.sh do runtime_env.sh): python contract_d.py <qualification/integration-brasileirao> <work> <out>
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from harness import Harness

BUILD = r'''
import json, sys
from pathlib import Path
from research_protocol import v2
from research_transport.spool import Spool
vector = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
task = v2.build_task("brasileirao", vector, episode_id="brasileirao:episode-1", proposal_id="cain:CONTRACT-D",
                     created_at="2026-09-28T00:00:00Z")
print(json.dumps({"task_id": task["task_id"], "vector_sha256": v2.request_content_hash(vector),
                  "spool": Spool(sys.argv[2]).put_task("brasileirao", v2.dumps_task(task))}))
'''
VECTOR = r'''
import json, os, sys
from pathlib import Path
sys.path.insert(0, sys.argv[1])
os.environ["BRASILEIRAO_RESEARCH_TEST_ROOT"] = sys.argv[2]
from tests.conformance import fixtures, harness
lab = harness.standard_lab()
value = fixtures.request("brasileirao:REQ-E2E-RUNTIME-001")
print(json.dumps({"vector": value, "policy": str(lab.policy_path), "objects": str(lab.objects)}))
'''


def main() -> int:
    mission, work, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    h = Harness(out, work, mission, "contract-revalidation-d")
    manifest = json.loads((mission.parent / "integration-crypto/fixtures/v2/FIXTURES_MANIFEST.json").read_text(
        encoding="utf-8"))
    stage_a_hash = manifest["domains"]["brasileirao"]["request_content_hash_verified"]
    (work / "vector.py").write_text(VECTOR, encoding="utf-8")
    (work / "conf").mkdir(parents=True, exist_ok=True)
    _c, lines, _ = h.run("Stage A vector (tests/conformance/fixtures.request) + conformance operator env",
                         [os.environ["CONSUMER_PY"], "-I", work / "vector.py", os.environ["BR_TREE"], work / "conf"],
                         public_stdout="full")
    got = lines[0]
    h.op = {"policy": got["policy"], "objects": got["objects"]}
    vector_path = work / "stage-a-vector.json"
    vector_path.write_text(json.dumps(got["vector"]), encoding="utf-8")
    (work / "build.py").write_text(BUILD, encoding="utf-8")
    _c, lines, _ = h.run("wrap the vector in a V2 task", [os.environ["CAIN_PY"], "-I", work / "build.py", vector_path,
                                                          h.spool], public_stdout="full")
    built = lines[0]
    h.check("(d) the Stage A vector is the one whose hash was verified against the Stage A result",
            built["vector_sha256"] == stage_a_hash, vector=built["vector_sha256"], stage_a=stage_a_hash)
    _c, delivered, _ = h.consumer("consumer")
    h.check("(d) delivered through the adapter_api", delivered and delivered[0].get("status") == "RESULT",
            got=[{k: d.get(k) for k in ("task_id", "status", "action")} for d in delivered])
    (path, result), = h.results()
    payload = json.loads(result["result"]["payload_canonical"])
    task = h.task(built["task_id"])
    h.check("(d) request generated by the adapter has the canonical hash of the Stage A vector (without client_ref)",
            payload["provenance"]["request_content_hash"] == built["vector_sha256"] == task["payload_sha256"],
            domain=payload["provenance"]["request_content_hash"], vector=built["vector_sha256"])
    h.check("(d) client_ref returned unchanged", result["client_ref"] == task["payload"]["client_ref"])
    h.provenance(result, task)
    return h.finish({"vector_sha256": built["vector_sha256"], "stage_a_request_content_hash": stage_a_hash,
                     "dataset": "sintético da conformidade (nenhum dado real)"})


if __name__ == "__main__":
    raise SystemExit(main())
