import hashlib,json,pathlib
import study
p='cripto-predictor';d=study.ROOT/'evidencias'/p;base=pathlib.Path('C:/CRIPTO/pesquisa-20260909')
notes={
0:'Historicalbacktest replaces simple observed-return/realizedfunding/barriers+portfolioholding chronology with logreturn*position, current fundingratecost proxy, compoundedoverlappingreturns andSharpepopulationstd*sqrt(n). Dropsfinite/horizon/symbol/kellyguards/inputSHA artifacts/scientificstatecapitalFalse, optionalmacro/edgefilter/thresholdgrid. finalverdictactualGO andloggerFase2AUTORIZADA reappear, Kellysweep nofrozenfamily/prereg. wfa_returns.json singleoverwrite/defaultJSON. Changes historicalonly; currentbase guardeddescriptivereplay.',
1:'Historicalbacktest advancedvariant retainsportfolioallocation/thresholdgrid butremoves input/provenance/frozenfamilyguards/macroavailability/calendarDXYcoverage, useslogratherthansimplegross/fundingcurrentproxy, barriersskipmissingprices/clampstoploss/takeprofit exactthreshold regardlessobservedprice/fullhorizonfunding; tradeexitscheduledfullhorizon. Sharpe/Sortino*sqrt(n) populationstd, oldGO/Fase2authorization andsingleoverwrittenreturns persist. Kellynotregistered, thresholdattempts usesattestation only+namesomitparametershash/family. Historicalnotcurrenteconomicvalidation.',
2:'Historicalreceiptcollector full323lines uses publicArbitrumRPC4readmethods whitelist≤500calls20MBtotal1MBresponse no retry/redirect/env, strictJSON/hash requestreceiptsfinally exclusivexb. Chain42161/finalizedfresh24h/13weekly84days2026-06..09 interpolatedbinary40steps adjacentparent identity, knownpoolUSDCaTokenABI15words/decimals6/configflags/cap andindependent normalized-income integerRAYreconstruction tolerance1. Boundedchainidentityreceipts sourceprovidertrustednot independentquorum. APIguardpersist scopeconsumesallow assets28 beforecollect. Decimal60/scaled-rounddown interest1000/5000/25000 USDC vsentryexit2/10/30 additionalcosts/depegloss1/5/100%; snapshotsliquidity/config notbetweenboundary transaction guarantee, all_in_personal_profitNone/future_profitFalse/unknownfundingbridge/tax/custody. calculate callerrows nofullsource/hashauthentication; noactualRPCstudy.',
3:'HistoricalRegimeEngine schema1noextra/features/traininghash, per-rowGaussianemissions withsingularcov impossible→uniform ifallinvalid, causalforward noemptyinputguard; onlyseed42HMMfullcov, assigns scaler/model before fullstate mapping, nofinite/retry/atomicstate. Returnedweights sharesglobaldict; pickle saveplainwb/load untrustedpickle initialexecutionrisk, missingfingerprintwarnaccept vscurrentreject. Currentbase schema2/extra validation/retries/atomicwrites distinct.',
4:'Twohistoricalattest_harness full138line implementations replacecurrentwrapper. Judgephase1Spearmanlower>0 andV3PSR≥.8+IClower>0 uses signal*fwd, noDD/costgate. Positivefixtures signalderivedfuturefwd intentionallyplanted sensitivitycontrol; independentnoisenulls, onlytwofixedseeds/n120/400 notpowerforrealdata. Dryrunharness assert noattestationwrite; expiring parses2expiryfiles thenwritesphase1first/V3second nocommontxn; underlyingcoreattestexternal. Exactvariants identicaldisplay bodies butSHA/path provenance preserved; noexecution.',
5:'Historical phase3Breport full replacement of unrelatedportfolio report: readsboundedbaseline/contracts/clocks/tests/funding thenassertpreservation/reproductionbyteeq, dynamicallyimports preservedadapter comparesnumericmaxcutoffv3 vsseparateobserved/economicallyeligiblev3B, writesreceipts/REPORT/REGISTRYatimport. LongPortuguese answers generatedfrom localinputs+literalnumericclaims(34acquisitions/58controls/12books410ms) notreverifieddatasets inthisread. Explicit UNKNOWN/TclockCAUSE_UNKNOWN/unprovenunitspayoff/settlement/currentonlymetadata, nofundingcashflow/noeconomicF03/F04. Historicalexperiments full184lines syntheticInstrumentexplicitunits/venue/chain/payoff/clock/hashfinite/conflict-asof/directFX; globalsocketpatch offline process only, reads outside repo absolutelegacy receipt/panels andoldinstalledCoreAST. F02preservationunchangedblock F03syntheticPITuniversecontrols notactualhistoricadmission. F04Decimalledger9fill-delay scenarios independentlyFractionoracle/localcash+orphan invariants assumes20%margin/nofunding/taxes/forcedimpact. F05AR1n160rho.6rep400 iidknowncovcircularblock8 coverage +256signmaxT4candidates fullnull/labelavailabilityoracles, no marketeconomicCI; writesexclusiveRESULTS beforeassertPASS, partialfails stillresult exists.',
6:'Historicalpreservedexperiments_v1 full174lines sameofflineF01-F05design/reference accounting/AR1maxT synthetic ascompanioncurrenthistoricalexperiments, butInstrumentdoesnot crossvalidatequantity/settlement/price units; receiptlen64only nothex; asof tiedversion silentlymaxfirst no conflict reconciliation; directFXamountnonfinite accepted samecurrency. F01controls narrow thuspass doesnotcertify guards addedlater. Noactualstudyexecution/PASSassertion fromcodeonly.',
7:'Historicaltradingstore diff removesdenseprovenanceschema6/sessiontext/collectorversion andallow_nanFalse; micros floattimestamp mayprecisiondrift. Eventdedup ignoreschanged eventclock andhashconflicts UNIONfirstLIMIT1 ignoresotherversions. Densevenue/symbol/sessionvalidation removed, session32hextransform elseUTF8 lateralwayshex corruptionofliteralID, hardcodedcollector. latestgroupssymbol/kind notvenue andloadsfullhistory. Compactionv1/v2 ONCONFLICTDONOTHING deletesonly matchinghash, missingpayload/metadataverification/sourcehashrecompute; conflictrows remain topbatch andwhileTrue cannonterminate beforefinalremainingraise (INFconditionalconflict), densemapsELSEcoerceunsupported. These historicalweaknesses notcurrentbasevalidatedcompaction.',
8:'Historicalmain inlineargs andruningestion replacingmodularservice; partialingestfailures noexit2 ifsome succeeds, skippedbudgetnotcountfailure. Removesanalysisruntimegate andsnapshot/inputfingerprint/preservedprompt/newsinputs, cacheassetpresence only (staleacrossdata/judgepolicy), migrateslegacyCSV duringanalysis, storelatestfeatures/source independentreads notsnapshot; allassetsfailed stillcanexportempty success, no outcomesreceipt/PARTIALexit2. Historybulk afterexportincludes cacheentries with originaltimestamps; storeclose notfinally/empty store raisesunclosed. LLMprefilter/providerbudget still present but scores remainnotprofit.',
9:'Historicalfeaturestore removesROmode/BegImmediate signalwrite atomicvalidation/conflictmetadata/finite andobservedvintage specialrules, batchdups firstwins samehashdedupignoresvalue/version/quality; onlynonnullconflictinghashreject. Deletesinputsnapshot API/inputescrow/predictionimmutableidentity andcloseddaycausalprice; predictionupsertcommit supportsreplacing samekey. Historicalcorrectionbundler full127lines atimport readsfrozenpreflightledger/status+publicsnap6 diagnostics, writesreportliteral1159tests49new etcnot freshverifyhere, mutatesvalidationreceipt/registry, copiesfreezefiles/denseevidence into exclusiveZIP/readsha manifests, safeextractresolve check+49pytestsubprocess then socketblocked offlineplanreplay. Actualhistoricalutility wouldexecute tests/reports onimport, notrun study; modelprofitfigures/waitingautomationlimits literalpreviousreportnot currentfacts.',
10:'Historicalanalyzerbacktest restoresmutableFeatureStore/migrateCSV, excludesfallback butadmitslegacyunverifiedinputs andnonfinite/outofrange score/price exceptprice<=0. Removescloseddayalignedsourceevaluationcontract descriptivebranch/return-onlydiagnostics; backtest closestrials/H6 again inclclosedfamilies, rawreturnsmetricwarningremoved andDSRlistusesonlyfiniteexistingSharpesnotcompletetrialdenominator/basis. Currentbaseproofstrictescrow/frozenstates nothistoricalweakness.',
11:'HistoricalVisioncollector futures/um-onlycachedZIP arbitraryflattenedpath noinputsymbol/rangevalidation, servesexistingbyteswithoutchecksum, optionalchecksumHTTPerror/absentsilentlycache, simplewrite nolockreceipt/atomic. FirstZIPentry decodedreplacement noCSVsize/singlefileverify, monthklines fromfuturesnotspot no2025microsecondconversion/closedbaravailability, all loadersduplicatepreserve OIinvalidrowsskip/wrongsymbolnotrejected. Fullhistoricalclosure122lines gathers42deliverables+selectedruntime/deps, forbiddenpathnamesnotsemanticsecretcheck, readsautomationACTIVE/targetexpected onlysnapshot nochange, SHA ZIProundtrip andspecifiedoldpackagehash/promptbyteeq, inventories noobserverlock; prepends3docs andwritesarchive/handoffliteralmanualreview. No actualclosure/git/networkexecutionstudy.',
12:'Fourfullhistoricaldeliveryutilities total402lines. Profitstagecopiesaudit/status/automationconfigurationchecks andliteral487/472/44/zero selection/46tests claims; appendsHYPOTHESES, packagegitbinarydiffreversecheck fixedbase, embedsdata/code/tests/requirements/replay adaptedrelativepaths/hashes. Payoffbundleatimport copiesresults, hardcodes30tests/ruff/pyright andreport10/13identity corrections/nulloutcomes/profitloss sensitivity, ZIPsha verification noactualtestsrun inutility. Correctionfinalizeratimport checks4freeze/preserved28results/oldrefs/runtimeautomationledgers andpublicplans offline socketblocked then hardcodes1159tests/runtime3785; newfreeze avoidsoverwrite onlyassert. Gitconsolidator realmutations ifinvoked verifiesCIhead+4jobs/exactmain/ancestors+oldworktrees/status/hash, ffmain, detachworktrees, ATOMIC lease deletesremoteextras/fetchprune/localbranchdelete; preservesuntrackedfredhash andmanifest/automation. Literal1170testclaimnot freshlocaltests. Noneinvoked; archivedinstructions nottaskauthorization.',
13:'Historicalqualitysnapshot removesnewcontractdescriptiveexclusion/H6power250/capitaleligiblefalse/evidenceclass, runsH6overallprices. PlainappendJSONdefault allowsNaN/no locks; publicstatus invalidJSON caughtthenoverwritten insteadpreserve, noatomic. Sealscurrentchain/manifestevenbrokenreport withwarning, removespriorpublicprefixanchor validation+lock publication protection. Historicalmigrationpacker102lines imports inventoryscanner, copiesautomation+originalprompt/gitstate/environmentmetadata; addsvenv andruntimeexceptbytecode/symlinks. 8threadshashstat pre/post then deduplicatedobjectZIP+hashreverify/finalmtime-size check; latercopiesruntime no originalruntimehashcomparison; no diskimage/schedulertransferclaim, hashes/inventory writesnopublishtransaction orsemanticsecretfilter.',
14:'Secondqualitysnapshot historicalvariant sameplainhistory/statusoverwrite/nopriorprefixchainguard andevaluationcontract exclusionremoved; retainsH6power250 fields unlikefirst. Fullbasisdelivery81lines verifiesoriginalrefs/automationledger/oldarchiveSHA, updatestrialsstreams completed+counts fromresults, freezesadditionsexecutionplanner, writesliteral42tests/28new/runtime3785 withoutrunningthem; packagesdata/V1gitshowhash/excludedcaches/stagingrequirements/FILESsha. Oldjobwrapper commandsscripts insteadinstalledoperationalmodules, removesexternalcoinmetrics/H8loop andDBartifactdependency; JobConfigdirect constructor stillvalidationthroughPydantic but differenttypedwrapper. Nojob/packagerexecution.'
}
notes[15]='Historical paper_report removes symbol/record identity, unique IDs, positive horizon, finite prices/position, individual horizon and entry/retrospective timing validation. Uses signal clock with uniform horizon, spot_1h and position*logreturn, sums log PnL and compounds 1+logPNL across potentially overlapping trades; empty/missing samples become zeros, drops initial equity. Removes UNVALIDATED/capitalFalse/portfolio unavailable states; telemetry gross unallocated values do not establish funded profit. Job variant removes external H8 runners, still JobConfig validation; no execution.'
notes[16]='Second historical paper_report shares block15 regressions. Historical ingestion removes finally receipt status, empty/mixed provider identity/request symbol/interval/OHLCV finite/order checks. Writes raw before derived features and builds all intervals with v1 default, no snapshot escrow. Partial errors can leave data without terminal ingestion receipt; no provider execution.'
notes[17]='Historical feature builder removes asset/time/finite/quality validation and funding uniqueness/order/equal8h checks; skips one extra initial window, return_8h actually previous available funding observation. Volatility up to24 closes/23 returns with sparse minimal samples silently filters nonpositive values and gives quality1. Duplicate price index last wins. Execution removes fill-id idempotency/conflict checks, absolute1e-9 marks tiny orders filled, terminal timestamp absent, duplicate fills accepted. Reconcile checks quantities only with unchecked tolerance, no fill identity/fee/times/order reconciliation; ledger retry ignores changed inputs, identity may change. Full historical runtime restore utility imports dependencies from relocated venv and validates manifests/frozen ledger/gzip/carry receipts, reports network0 without socket guard, subprocess no timeout. Not invoked.'
notes[18]='Historical paper trader removes frozen-family, symbol/finite Kelly/reference price and signal-age checks; append no lock/fsync, duplicate race and corrupt-lines ignored. Omits actual timestamp_entry and explicit shadow capitalFalse, uses latest historical signal price. Old spot collector removes finite/identifier/timestamp validation, stale state not invalidated on reconnect, snapshot consumer may survive snapshot failure, shutdown may wait idle messages/backoff without cancellation. Default database relative cwd. Historical altcoin tests omit current comprehensive universe/BTC/external benchmark/week/cost controls and reacquisition/error status assertions. Historical gaps only; no execution.'
notes[19]='Historical jobs still H8 loop but external Coinmetrics removed, script entrypoints versus installed modules. Funding collector drops page/range/record finite symbol validations, end-exclusive loop; append CSV dedup only previously persisted timestamps (within new batch duplicates survive), no value conflicts/atomic/locks, sorted load trusts records. Factor DSL removes constructor arity/type/finite validation, bool/fraction truncation lag/window, equal-length/overflow/nonfinite output guards; lag beyond sample length expands output, zscore current None can fail; raw features preserve NaN. Historical only.'
notes[20]='Historical HMM schema1 retains retry/extras but removes duplicate extras/finite/empty/equal-length checks and training hash; assigns scaler before successful fit, shared global weights mutable, unsafe pickle trust unchanged and save non-atomic. Legacy missing fingerprint warning permits load. Scalar emissions not vectorized. CLI lacks read-only status/history/research/migration/recovery and runtime isolation/redaction/error sanitization; directly imports main and runs, separate ingest disabled. Historical only, no imports executed.'
notes[21]='Historical hypothesis loop permits JSON NaN and recursion unhandled, DSL guards weaker; horizon/frequency/matching target length/finite pair validation removed, zip truncates and block length assumes daily. Proposal history lives package directory, malformed history becomes empty then overwritten, append lacks locks/atomic/parent mkdir; provider consumed before history validation, concurrent duplicate races. Factor variant shares block19 complete regressions. Full historical downloader import starts2 threads network for365day funding/spot/mark then BCB, saves even HTTP error bytes before raise, known_at before HTTP not response receipt, hash rawbytes, cutoff/dedup/progress guards funding only; no economic simulation or study execution.'
notes[22]='Historical OI/spot collectors remove range/page/identity/finite/nonnegative checks and shared record_io; append dedup against old timestamps only (new duplicate batch persists), no conflict/atomic/lock, load sorted raw. OI floor adjusted now30day warning paidfeed; spot includes unclosed bars rather than available-at cutoff. Quality scorecard removes audited cadence-bin coverage/median-p99 measured ingest latency and negative-latency quarantine, delegates core generic scorecard; historical scorecard semantic difference only.'
notes[23]='Historical trading contracts remove finite guards throughout, fill identity/duplicates/before-created-before-accepted and terminal ordering checks; quantities allow absolute1e-9 excess and remaining may negative, mark prices unchecked, timezone offset None insufficient guard. Historical conftest twovariants no temp isolatedpaths/secret purge, setdefault preserves ambient credentials and tests events under repo; removed power fixture. Full phase3 synthetic adversarial harness blocks socket connect, normalized roundtrip/hash/provenance/temporal boundaries and intentional contradictions, all economic_join refused, hardcoded bugs_scope test oracle only; outputs before assert may persist failed results. No fixture/HTTP/runtime execution in study.'
notes[24]='Historical phase1 removes consistent serving snapshot/prompt/news/input escrow and radar transitions/partial radar failure statuses; latest source/features independent reads and degradation determined news emptiness. Redaction historical tests two variants lack chained traceback/cache exception/future handlers/error-event persistence cases. Microstructure watchdog treats snapshot as ordinary stale, no future receive/session mismatch and finite horizon checks; daily coverage boolean1 for any observation instead UTC-minute occupancy, no resync health/ingest-before-receive validation, depth simplistic nonincreasing sequence rather than contiguous per-session range, snapshot crossing omitted. Secret scan historic regex narrow token assignments/rglob untracked excluded dirs but lacks resolved inside-root containment; reports fingerprints without value. Historical gaps only.'
notes[25]='Second historical secret scanner same block24 semantics. Signal tests omit thresholds/confidence overrides and regime posterior fixture sums conf<1. Macro tests assume calendar-known/business-day lag implicitly instead explicit provenance opt-in, still assert weekend causal alignment. Historical H8 runner drops horizon/oneasset/unique increasing timestamp checks, index i+days*3 instead exact event time implies gaps bias; no finite returns and division before log may overflow. Path package-dir JSON invalid history empty then overwritten plain noatomic/lock; does not prevalidate evaluations before provider, blocklength drops3observations/day scaling. No economic validation.'
notes[26]='H8 runner variant same block25. Observation quality JSONL lacks lock/atomic/full payload hash recomputation; existing forged hash trusted and duplicate race. Generic source quality replaces audited clock/bin wrapper, receipt-available latency incorrectly uses published_at, independent divergence unknown hardcoded0. Watchdog two variants reads malformed heartbeat unsafely, requires environmentkey, no aware/future timestamp validation and negative age passes, opens mutable migrating FeatureStore instead SQLiteRO, missing database-error downgrade and DEGRADED source violation. No execution.'
notes[27]='Historical book/update/fill removes finite/unique-price guards and side validation. Depth updates mutate before validation, empty/crossed state can persist; no cross-book check, fills absolute1e-12 produce tiny fully_filled evenzero, iterative subtraction versus fsum. Impact finite checks removed. Altcoin test variant omits full12week cost-negative/missingweeks None/reacquire/status checks. Cache variants remove inputfingerprint/rootentryvalidation/futureage bounds, save overwrites wholesale non-atomic/no lock with NaN and mutates input setdefault; corrupted priorcache not preserved. Full decide utility emits literal sixclockhypotheses/eighteen evidence requirements/F03F04BLOCKED and UNKNOWN units/capitalfalse; analysis assertions based prior recorded artifacts not independent new capture. Full finish_checks invokes ruff/wheelsmoke and records hash/import origin demo4outputs ifrun, hardcoded priorbuild explanation; notrun here.'
notes[28]='Historical book variant shares block27 finite/atomic/tiny-fill issues. V3 pipeline no symbol path validation/cache sample trimming/closed bars, ingestion_at from filemtime not observedreceipt, models reuse singlefilename without schema+trainingdata hash; signals common signals.jsonl and DESCRIPTIVE_REPLAY metadata removed, possible stale model across samples. Full baseline utility readonlySQLitequery_only/inventoryhash/gitremote/packageversions, schema/count/snapshotmetadata not economic inspection; noexecutionstudy. Costmodel drops finite/nonnegative guards, friction2legs equalnotional ignores exit ratio, constant rate*horizon/8 funding proxy. Job tests use sleeps insteadready handshake, redaction combined timeout maybufferlost; health tests lack offsets/future/malformed fixtures.'
notes[29]='Historical CCXT variants retains finite but removes positive limits/timestampint/dedup/range/OHLCVgeometry and sorting, doesnot copy symbolmap; asks limit instead limit+1 then filters open bars mayundersupply; close exceptions silent. Historical exporter no formula escaping, second-resolution collisions, directory preexistence and directwrites noatomic. Full freeze utility calls carryverify and freezesfiles exclusive but test57/new8/ruff/pyright/precollection booleans literal not checked. Full package utility copies/hashverifiesbounded inputs/reports/ZIP/testzip/preservationsha but prior request/pathspolicies, not studyexecution. Conftest retains powerfixture but lacks ambient isolation. Old redoma test malformed OHLC/source availability and mocks runtime; noexport failure/snapshotinputpersist assertions.'
notes[30]='Full distribution RECORD verifier hashes only recorded hashed files, reports missing/mismatch and LF-normalization comparison; no assert absence/untracked/baseline wheeltrust, noexecution. Distribution tests omit source archive security. Exporter shares29 formula/collision/atomic gaps. Settings loads adjacent .env, APIguard defaultFalse, NaNallowed/pacingTTLhorizon guards removed and ingestrequiresLLM/newssecrets because mode distinctionabsent. Dailyfeatures ignoresdaily/duplicate/gapvalidation and raw basevolume labeledUSD, no auditedversion; harddata keepsNone/Inf exceptNaN. DXYtests expect inferredbusinessday publication rather than receiptvintage. BAT bypass local-root launcher and uv sync mutates env ifrun. Adapter retains frozenfamily but no trial/fingerprint/costfriction/verdictcalibration, checks costmodel registry only; no capitalproof.'
notes[31]='BAT andfeature variants same30. Full package-finalizer consumes prior verification PASS62 and writesarchiveSHA/HEAD into reports, no freshtests. CCXT variant same29 but loggingretained. Full source patcher rewritesattest tostage two outputs before canonical sequentialwrites; nojointatomic and rootdirtywindow concern addressed only originalgeneration. Indicators remove finite/period/MACDfastslow/Bollinger validations, RSIflat returns100instead50. Calendar published_at eventday removes observedvintage+unverified flags (historical lookaheadrisk). Signaladapter tests no calibratedmock/defaultrejecttest. Alignment chooses most recently available observation even oldevent revision, removes monotonic latesteventwinner and negative staleness check; old delayed revision can displace newer economic event.'
notes[32]='Historical registry tests register through _NOGATE instead powerattestation fixture and permit legacy implicit migration read. Macro calendar tests expect FOMC8only vs33combined and eventday publication rather than observedvintage. Adapter tests omit calibration default rejection. Scoreengine nonfinite inputaccepted/minmaxNaN propagates; technicaltrend/momentum zero now bearish instead neutral and no finite/type checks. BAT bypassroot launcher/uvsync; alignmentsame31 oldrevisiondisplacesnewerevent. Budget tests noisolateddb/durable resetproof, FearGreedcachedlistold. News cache noTTL/received_at, processlifetime stale titles masquerade freshlyreceived. Quality tests explicitly overwrite corrupt/nonUTF8 status rather thanpreserve; facade omits explicitconfiguredCoinGeckoapikey. Historicalnotcurrent.'
notes[33]='Calendar publication same31. Coreintegrity historical pin variants3.0/4.0 and3.2/4.1 require no packagesdir vscurrent research-exportallowed, notcurrentinstalledversions. Businessday accepts bool/noninteger count. Prefilter variants remove finite/bool checks NaNmaypass thresholds. Plugin hardcodesH6ACTIVE/READMEtruth/ownerrotationclaim rather than typedcharterdynamicstates; remainscapitalFORBIDDEN. Settings variant same30 except APIguardTrue retained. Equivalence variants finite/no meaningfulindicator/alignment enforcement removed and empty/allskipped aggregateTrue; maydeclare equivalent unaligned/directuntimestamped series. Adapter variant moves calibratedcostpolicy check before inactive signal return, stillverdictguard/trialfingerprintretained.'
notes[34]='Derivatives v1 hashesNaNpermissive and labels event_at as publication even retrospectively ingested records (published_at_exchange flags unproven). Historical paperreport tests expect emptyPnL0, noinitialequity, logPnL .09531 insteadsimple .1 and no retrospective/DDNoneassert; observation tests mandate firstvalidwins conflicting batch vsatomicreject. Timeindex sharesmutableoriginaldict and no negative tolerance validation. Chartertests expectH6collectionimmature vscurrentclosed. Paths localrootconfigurationremoved. Stocksadapter tests assume ref+11day publication notreceipt and one OHLCfixtureinvalid; source code is copiedcrossdomain insideCrypto historicalsource. Predictionappend tests formattingonly. Historytests implicitlegacyload/bulkafterexport source assertion. Installedwheelchecker older2.3/3.1 exactURLSHApins. Serp errorandlogger rawexception can exposeproviderbodycredential; noneexecuted.'
notes[35]='53historicalobjects reviewed complete diff including executable constants. Several exact executable-equal bodies (empty diffs) derive reviewed migrations/circuitbreakers/governance/groundtruth/orderbook/gate/PBO/PS1 utilities with SHA provenance and opcode reconstruction, no new behavior. Changes: timeindex mutabledict/negative tolerance; removesmigration0019 snapshots; CoinGecko auth no explicitsettingskey; watchdog localdate/logs/raw webhook exception/noalertmkdir and TypeErrornotcaught; reset_for_test deletesdurable api_budget; paths bypasslocalroot. Olderbackup scriptmodule tests, stocks telemetrydefaultCrypto domain, implicitlegacy test readers/corruptproposalempty, pluginH6ACTIVEtests. BTCbasis uses frozen spec costs directly instead approvedcost_scenarios helper. Vision savesambiguousspot_1h. Tradingreport sameinstrument position notional lastwins insteadsum understates gross/concentration, leverage separatecalculation; crowdingclock omits1hcloseavailability, history drops input_snapshot, __version__1.0.0 historicalonly.'
notes[36]='Fivefinaltinyhistoricaldiffs: groundtruth uses implicitlegacy backtest load; copied Stocks DPL ingest omits explicit stockdomain; trading orderfixture uses randomIDnotmatchingliteralfill ID (oldcontractallowed); backup tests expect scripts module; crowdingclock exchange timestamp lacks1hclosedbar shift. Exactline reconstruction verifiesdeletions/additions; no testsrun orcurrentdefectassertion.'
out=d/'archive-derivation-2-notes.json'
previous=json.loads(study.read(p,out)) if out.exists() else {}
idx=json.loads(study.read(p,d/'archive-applications-review-index.json'))
assignment=json.loads(study.read(p,d/'archive-derivation-assignment-2.json'));by={r['path']:r for r in assignment}
for block,note in notes.items():
 for path in idx[block]:
  r=by[path];source=study.read(p,base/path);digest=hashlib.sha256((base/path).read_bytes()).hexdigest();assert not r.get('source_sha256') or digest==r['source_sha256']
  reconstruction=None
  if r['base']:
   parent=study.read(p,base/r['base']);assert hashlib.sha256((base/r['base']).read_bytes()).hexdigest()==r['base_sha256']
   pl=parent.splitlines();sl=source.splitlines();rebuilt=[]
   for tag,a,b,c,e in r['opcodes']:
    if tag=='equal':assert pl[a:b]==sl[c:e];rebuilt+=pl[a:b]
    else:rebuilt+=sl[c:e]
   assert rebuilt==sl;reconstruction='all-opcodes-exact-line-reconstruction-verified'
  previous[path]={'path':path,'source_sha256':digest,'base':r['base'],'base_sha256':r.get('base_sha256'),'base_review':'integral semantic review other team agents; see source coverage','review':'full-diff-including-deletions-plus-integral-base' if r['base'] else 'full-body-semantic-read','reconstruction':reconstruction,'semantic_integral_certified':True,'block':block,'evidence':f'raw-source-archive-applications-{block:03}.txt','notes':note,'execution':'not-executed','scope':'historical-only-not-current-implementation'}
study.save(f'evidencias/{p}/archive-derivation-2-notes.json',previous)
study.save(f'evidencias/{p}/archive-derivation-2-coverage.json',list(previous.values()))
study.log(p,base,'Progresso semantic historical assignment2',0,str(len(previous))+' objetos revistos',artifacts=p+'/archive-derivation-2-coverage.json')
print(len(previous))
