import study,json,pathlib,hashlib
notes='''Kelly negative edge clamps0 invalidNaN/inf/prob/fraction rejects; futuremarket notfresh; fairodd<1/overflow fail.
DispatchProxy Redis mock reflection MSE: match/job/run/channel exact correlation, malformed/expired no signals; changedwithdrawnquote afterstateawait invalidates; finalfence mocknegative returnsnone; eligible synthetic sig CapitalEnabledfalse. Doesnot executeLua.
Conditional RedisRuntime real-disposable tests lostnotification startup/loop recovery readyindex/outbox; TTLpreserved/dedup, expired/superseded rejected; wrongoutboxtype no dedupconsume; auditfailure stillretains; MAXLENexact10000; malformedhints cannotstarvevalid. Fixturesprices synthetic.
Kelly knownnumeric oraclep0.5odd2.5fraction0.1=1/60; formulaengineering notprofit.
Crossprocess conditional LINEUP_E2E_PYTHON, explicitloopback26380DB13 serverrunid; childsyntheticPython filebarrier intentionallyloseswake; requestretained then1sig, duplicatewake dedup; actual Worker+hotpathsmoke syntheticVORP resources;120sstartup/40swait limits. Notexecuted.
Mock invocation registration verifies sameevent+inputs same idempotencyhash/differentguid; partial/completed/newcorrection identities differ; restart deterministic. Lua replies simulatedversion1.
RedisRuntime latencyretention max2percentile, windowexpires no newwrites, T4beforeT3 rejected and staleCAS cannotreplace; sameT3invalidrevision removespercentile. Config testsbudget0/-1/NaN noRedis.
RedisRuntime audit olderT3cannotreplacecurrent/renewTTL; historicalsamplecounts2; duplicateT3 preservesT4. Counters/window universes separate.
RedisRuntime stream own fixtures11players: pending input beforestartup,4failures kept, registrationthencrashbeforeACK replay no newversion; poisonnostarve/cancelnoACK; malformed/expired/future quotas rejected digestonly nosecret; transientRedisrecovery. Validation16invalidlineups beforeVORP.
MarketFeed parser reflection synthetic normalizedcontract: legacydefaultdisabled; statusrevisionnotresurrect, observationage notreceipt, duplicatekeys/conflictingrevision invalidates; identity/clock/types/totalline2.5 invalidwithdraw previous; duplicatekeepsreceipt/newrevisionresolves; oversizemissing no market. No WSS livebridge.
Model branches missingoptionalallprices allowed,blankids refused; overround/clockdeltas; URI ACL/defaultdb parse no network.
OperationalSettings envscope restores5vars, assemblyparallel disabled; absolute isolatedpaths/missingredis/schemevalid; no artifactexists validation.
RedisEndpoint URI usernamepassword escaped/databaseTLS preserved; malformeddatabase/queryfragment rejects without echo URIcredentials.
RedisProtocol serializer fieldnamesV2, null/missing unavailableprices; nonnumeric no coerce; unknownV1/version/id reject; statecanonicalInt64 string nofloat; excludes0/01/-1/exponent/overflow. Schema divergence missingprices runtime explicitly allowed.
RedisRuntime watchdog acknowledgment survivesrestart; correctionkeepdeadline duplicate repairsdeletedindexbeforeACK; badindex preventsanyregistration/ACK; stalecleanupCAScannotremove newerindex.
RedisRuntime health dotnetchild tests Redisalive alonefails, requiresMSE+inboxsameinstance/sessionTTL; leaseowner cannotoverwrite/cleanupnewowner; malformedpermanentexpiredfails; poll heartbeatrenew/stopcleanup;5s expiry whenloopsstop. Noeconomicreadiness.
RedisRuntime model declaredinputs mandatory unlesssynthetic; acceptedElo1630/1480 andcoveredpositions; changedcontext cannotmix sides; future/hash/team/position/naiveclock rejectsbeforestate. Resources syntheticfixture.
RedisRuntime fencing exactstateCAS/dedup/newrun sequence, precisiondoubles preservedLua; finalread-race rejectsstalerun andmissingTTL/pending/snapshot/deltas; watchdog no stale restore; concurrent sides merge/order duplicatesignored; DropOldestnamesactualevicted; transient3retry anduncertaincommittedreply dedup, permanent1attempt.
Runtime fixture gate vars LINEUP_TEST_REDIS_URL/RUN_ID or skip; loopbacknondefaultDB15/40hexrunid andemptyDB mandatory, cleanupchecksidentity/ownedkeys/tempdir. TestsVORPwarmup synthetic/fallback, market/cache, latency percentiles emptyzeros, versionedinvocation/signalCapitalfalse, eligibleedgesKellycap5%, cancellation/watchdog/immediatepublish. Some negative no-market test onlyabsenceexception not signal assertion. No execution here.
KernelContracts records V2required identitystrings/statecanonicalInt64; optionalmissingodds becomeNull, finite>=1; MarketOdds freshnessstatusACTIVE/observation30s/pre-kickoff; declaration source/bookmaker not authenticated. Signalclassification SimulationOnly.
LatencyRecord derivesdeltas declaredcaptureT0 SourcePublishedAtnull; budgetspositivefinite/nonnegativeE2E; T3fixedwidthticks Lua stringorder; BetSignal capitalfalse economicUNVERIFIED allmarket/modelprovenance metadata.
LineupEvent arrays+capture+optionalModelInputs; state records bothsidecapture/hash/modelidentity/team/deadline original; no infermissinglegacyclock. VarianceWideningSignal notification not actualmodelvarianceapplication.
LineupModelInputs.Validate explicitawareclocks learned<=fitted<=available<=decision<kickoff/capture<kickoff; identity/Elo/hashcoveredpositionsGKDFMFFW; sortedpositionscontextSHA. Version onlynonblank; hash/clocks no producer authentication.
OperationalSettings requires5envvars absoluteartifacts/DBpaths and sports!=market; Redis/rediss URI TLS ACL decoded/dbnonnegative andtimeouts/reconnect. DBnamesonly notopenedbysettings, symlinkalias notchecked.
Program operationalsettings firstevenhealthcheck; healthRedis+loops timeout3s, hostmandatoryappsettings+LINEUP_env; hostedwarmupVORP→marketcache→MSE→Worker→latencyreport5min. Doesnot test artifacteconomicquality.
KernelRedisProtocolV2 Lua standalone boundaries type+ACLpreflight beforemutations; register CASlineups/current, deterministicidentitymarkerduplicate/superseded, INCRstateasstring replacesplaceholder avoidingcjsonrounding; pending60s/currentstate6h. PublishSignals finalsamecurrent/fair/requestcompleted/result/snapshot+TTL checks, exactbatchidentity, MAXLEN10000outbox+dedup+ZREM thenpcallnotifications. ReadReady RedisTIME ZSCANcursor32hint; watchdogdeadlineimmutable guards fallback invalidatesoldfair/current/lease/index. RequiresRedisACLcommands/XACKDEL elsewhere; noClusterhashslots protocol.
LatencyAuditService Lua receivedtime-window2days/max10000, pruneatomicpercentilesfloor(n*q); stringT3order preventsoldlatestoverwrite, identicalretryTTL/T4preserved butreceivedwindow readded onrecord; invalidclocks removesmember. Processcounters allsuccesscalls versusuniquevalidwindow differ; MarketRead exactCAS KEEPTTL. No authenticatedpublicationlatency.
LineupStreamConsumer group0-0 XAUTOCLAIM1s cursor16 thenfresh16; JSON64KiB/events11players/max30subs; captureage/future5min; rejection streamMAXLEN1000SHA/reason ACKDELatomic afterpreflight, handleexception remains pending. SuccessACKDEL afterhandle/cancelguard; Redisfailure/NOGROUP recreation boundedloop. DoesnotvalidateJsonduplicatekeys universally.
MarketOddsCache normalized-market/v1 explicitconfiguredWSS/source/bookmaker bridge; not nativebookmakerprotocol. Defaultabsent feeddisabled; bounded256KiB/depth16topduplicatefields; awareclocks/revision/source/FT/line2.5/activeprices;30s freshness, revisionconflict/invalid/suspend withdraw, disconnectUNAVAILABLE preservedfence. Synthetic legacy explicitallow only, no samequoterevisioncaps there. Quote sourceclocksdeclarations not commercialexecutability.
MarketStateEngine listensnotify+100msreadycursorpoll; exactfair/currentidentity/snapshot checks and finalLua refences afterawaits; localquote stillsamefresh afteraudit thenpublish. Five selections edge=pmodel-1/odd; FractionalKellyclamp[0,5%]; min2/max15percent bydefault; LatencyBudget300ms onlyloggingLATE noabortgate. T4 capturedBEFOREedgeactualarithmetic (commentheaderdifferent). Invocationguid+event/inputSHA deterministicclaim; Redisregister ownsstateversion. No brokerorder.
VorpStateService warmsJSON beta_players/replacement/titularidade once/hash; finitecoefficients/probs[0,1]; declaredsum requiresplayerorpositioncoverage, legacyunknownfallback0; arraysreturned mutable reference, classready no lockingneededstartup. ArtifactSHA notscientificprovenance.
WatchdogStateStore Lua RedisTIMEdueZSCAN32; synchronizeexactstate/currentCAS beforeindexrepair, missing/completeremoves; preservesdeadlineandnoinventclock, ACLwritepreflight.
WorkerHealth owns instanceMachineName+sessionGUID rolesMSE/inbox, renewal5s cannotoverwriteotherowner; cleanupCAS; checkerbothvalidTTLsameinstance/sessionandprotocol. Livenessonly notdataprogress/economicreadiness.
Worker legacyPubSubDropOldestbounded512 mayloseinputs after3transientretries; durableStream parallel consumer recommendedACKafterregistration. VORPwarmup; inputsmandatorydefault; eventhashsamecaptureduplicate/conflictearlierignored; context/teamidentityimmutable, CASmergebothside/preservedfirsttimeout55min; auditfireforget. Watchdogdurableindex60s capturesdeclarations andfallbackinvalidateskernel; wideningONLYpublished, not observedvarianceapplication here. Immediatequeueoverflowfallback publishes/audits withoutsameatomicstateinvalidation, deliveryofnotificationnotdurable.'''.splitlines()
j=json.loads(study.read('brasileirao-shared',study.ROOT/'evidencias/brasileirao-predictor/semantic-pending-by-class.json'))
rows=j['files']['C#'];assert len(rows)==len(notes),(len(rows),len(notes))
out=[]
for r,n in zip(rows,notes):
 s=study.read('brasileirao-shared',pathlib.Path('C:/BRASILEIRAO/brasileirao-predictor')/r['path'])
 out.append(dict(path=r['path'],sha256=hashlib.sha256(s.encode()).hexdigest(),review='integral-semantic-read',notes=n,execution='not-executed-in-this-study'))
paths=['dotnet/LineupWorker.Tests/LineupWorker.Tests.csproj','dotnet/LineupWorker/LineupWorker.csproj','dotnet/LineupWorker/appsettings.json','dotnet/LineupWorker/packages.lock.json','contracts/redis-fair-odds-v2.schema.json','contracts/redis-protocol-v1.schema.json','contracts/redis-protocol-v2.schema.json','schemas/odds_snapshot_v1.json']
for p in paths:
 s=study.read('brasileirao-shared',pathlib.Path('C:/BRASILEIRAO/brasileirao-predictor')/p)
 n='net10.0 Worker Hosting10.0.10 StackExchange.Redis3.0.17; tests xunit2.9.3 sdk18.0.1 runner3.1.4 coverlet6.0.4; workerlock32packages resolvedhashes, testproject no trackedlock identified; configedge .02-.15 Kelly.25 300ms/queue512/55min/6h. BetSignalChannel configdeclaredbutactualservicehardcodes bet_signals. SchemasV1archived/V2statepositive19digit pattern runtimeaddsInt64upperbound; fair schema requires5pricekeys+noextra whileC#allowsmissing/extra. Odds_snapshot Pythonseparate contractoddspapi_v4/homologatedfalse/hash/lifecycle, notnormalizedmarketWSS.'
 out.append(dict(path=p,sha256=hashlib.sha256(s.encode()).hexdigest(),review='integral-semantic-read',notes=n,execution='not-executed-in-this-study'))
study.save('evidencias/brasileirao-predictor/shared-dotnet-notes.json',out)
study.save('evidencias/brasileirao-predictor/shared-dotnet-coverage.json',[{k:r[k] for k in ('path','sha256','review','execution')} for r in out])
study.save('evidencias/brasileirao-predictor/shared-dotnet-review.md','# Suplemento .NET / LineupWorker\n\n34 C# (inclui19 testes) e8manifestos/config/schemas lidos integralmente. Nenhuma compilação/teste/Redis/WSS executada. Fonte checkoutlocalprimário, não remoto ou alternativa. SHA físico leituraUTF8 preservada e REGISTRO.log.\n\n'+'\n\n'.join('## '+r['path']+'\n\n'+r['notes']+'\n\nSHA256: '+r['sha256'] for r in out))
study.save('diagramas/brasileirao-dotnet-sequence.mmd','sequenceDiagram\nparticipant P as Producer declarado\nparticipant R as Redis standalone\nparticipant W as Worker CSharp\nparticipant K as Kernel Python\nparticipant M as MarketStateEngine\nP->>R: XADD lineup inbox\nW->>R: XAUTOCLAIM / XREADGROUP\nW->>W: Validate context / VORP lookup\nW->>R: Lua CAS snapshot + INCR + request pending\nW->>R: XACKDEL após registro\nK->>R: Recupera pending / registra fair result TTL\nM->>R: ZSCAN ready / lê result\nM->>M: Quote corrente / edge / Kelly simulation\nM->>R: Lua final fences + outbox + dedup\nR-->>M: retained batch count\n')
study.log('brasileirao-shared',study.ROOT,'Revisão semântica manual CSharp testes manifestos schemas',0,'42 arquivos integral; nenhum exec',artifacts='brasileirao-predictor/shared-dotnet-notes.json shared-dotnet-coverage.json shared-dotnet-review.md')
print(len(out),'reviews')
