import study,json,pathlib,hashlib,ast
notes = '''API TestClient/FakeLLM: saúde e oito etapas; rejeição de entrada/intenção; preferências antes da geração, reabertura e isolamento; busca indisponível não bloqueia perfil.
CLI subprocesso DB inacessível: exit1, mensagem CAIN sem traceback.
Config monkeypatch ambiente: resolução relativa, provider instanciado sem inferência, tipos/chaves inválidos rejeitados.
Functional FakeLLM seis etapas e correções: real_llm=false/qualidade humana desconhecida; falha auditada sem resposta nem retry; fake via CLI bloqueado.
Harness matriz smoke 324 respostas sintéticas: comparabilidade de entradas, cegamento metadata, isolamento A/B/C, orçamento caracteres, falhas e metadados detached; não mede convergência real/validade embedding nem qualidade humana.
Recursos empacotados: bytes iguais, cwd independente, identidade de código executado/hash dependência; git_commit não adivinhado.
Quality dataset 14 casos dev/holdout: dois braços entrada idêntica, JSON estrito/rotas/fatos por heurística/citações; código somente AST, inclusive retorno errado aceita sintaxe, nunca execução; winner/humanquality desconhecidos, falhas retidas.
EvaluationV2 tipos/duplicatas/NaN e literalidade; semântica requer revisão; isolamento saída sem overwrite; attestation loopback precede mutação; controles e catálogo congelado. run v2_integrity é assertion declarada, não executada aqui.
Capabilities fixtures ResearchService e modelo instrumentado: etapas/idempotência/aprovação/retomada/revogação/cancelamento/lease expirado; relações literais; MCP allowlist e stdio subprocesso; API compartilhada e streaming mock. Não exercício real LLM.
Permissions Path.open guard: revogação impede leitura da fonte; history redige sob política atual.
Archive DBs/documentos temporários: backup/restore identidade e unicode, sem overwrite; hash adulterado/missing document rejeitados antes conclusão.
Compound field lookup sem inferência: estado/trial/motivo/amostra completos e condicionais; identidade A72 versus A720, unicode; campos ausentes e revisões conflitantes explícitos; interpretação não redefinida como lookup.
Conversation modelos dublês: cotidiano evita retrieval; aritmética exata frações e limites sem execução; informação antiga não vira citação; hipotéticos/literal output encaminhados intactos, não avalia qualidade desses outputs simulados.
Delivery DB temporário: record_turn falha antes/depois commit recuperável sem nova geração; completion/outcome transação única; processing abandonado bloqueia rerun; dois apps concorrentes geram uma vez; os._exit subprocesso três checkpoints. Não queda física de energia.
Evidence selection: offsets e chaves tardias, negadores e condições inteiros, identidades unicode sem substring; JSON duplicado abstém; limite indivisível omite; mock paginação; revogação impede entrega.
Full audit: tipos config estritos; perfil/código lazy sem embedding; limite transport 4MiB; documento alterado rejeitado; caminhos absolutos sobrevivem cwd; servidor loopback redirect bloqueado sem segunda chamada.
Language preference CaptureLLM: en/pt instrução chega prompt, payload original preservado, scope session/user; não comprova que modelo obedece idioma.
Greetings modelo proibido: respostas determinísticas seis saudações auditadas; conteúdos adicionais/intenção explícita não engolidos.
Grounded analysis PLAN fixtures e PointerModel: lexemas JSON escaped/offsets literais, paths identidade exata, extração sem inferência/permissão geração; unlabelled tables e duplicatas abstêm; revisão gerada não certifica semântica. Orçamento inclui provenance/preamble/header inteiros; separa seções/publicações; prior proposals omitidas antes evidência; excesso resposta rejeitado.
Historian quote choices enum somente campos completos literais e limitados; duplicatas/fragmentos não viram escolhas; revogação durante inferência descarta output.
Quote serialization: substring JSON exata aceita; aspas adicionadas/campo omitido/reconstrução rejeitados, sem reparação automática.
Hybrid runtime modelo duas chamadas: classifier resumo depois agente; razão llm_classifier registrada. Modelo sintético.
Independent review: CRLF/unicode e pointer escaped verificáveis; ausência/ambiguidade sem fallback; condições multilinha inteiras; protocolos antigos leitura/cancel idempotente, sem nova execução; orçamento abstém explicitamente.
Mandate completion API lookup estado/trial/missing sem LLM; historian bundle metadata sem conteúdo; selection subprocesso source-first e receipt adulterado/policy revoked/pointer errado impedem verification.
Persistence SQLite reopen: índice lexical reconstruído reproduz ranking/filtros; snapshots detached; user mismatch rejeitado; decision SQL triggers impedem UPDATE/DELETE/REPLACE e reabertura mantém append.
Plugin UppercaseAgent registro dinâmico e intenção uppercase oito etapas/log; registry congela após execução, nova inscrição rejeitada.
Preference persistence: correção/provenance sobrevive reopen; forget não ressurge de memória legacy; fontes retidas; index failure mantém canônico; duplicate signal rollback/revision stale; legacy JSON migra compatível; top_k/user/currentrequest isolados.
Recent context: fatos sobrevivem reopen sem overlap lexical; usuário/projeto/sessão isolados e prefs antigas excluídas; followup usa conversa sem classifier; comandos saída não puxam resposta antiga; ordem cronológica. Modelos assertions de contexto, não qualidade geral.
Research completion: política revoked antes/depois model failure não retorna fatos; API history reabre session própria; corrupção filtros/membership não falseia ausência e rebuild restaura; duplicate JSON output rejeita; braços synthetic duas chamadas utility INCONCLUSIVE.
Research failures: projeção OSError rollback com receipt separado; audit unavailable erro explícito; JSON quotas/depth; origin adulterada rejeitada; backup WAL snapshot comprometido apenas. Windows launcher skipif fora Windows, fake python impede provider startup e serviço estranho não parado.
Inspection synthetic: namespaces/revisões/supersession declarada apenas, missing/cycle/status findings e UTC ordering; política scope e recheck, sem escrever histórico/LLM; offline API/CLI; quotas e corrupção explícitas.
ResearchL0 fixture define grants/publications synthetic: idempotência, namespaces e concorrência 8 imports/1admitted; conflito rollback; ordenação revisões e ambiguidade preservadas; malformations/path/symlink, quotas, corruption/rebuild/backup, SQL pagination. QuoteProvider só extração literal e síntese livre rejeitada; Fake simulation explícita. Symlink test skip se privilégio indisponível.
Research roots policyV2 scope-bound dois roots mesmos filenames, consulta offline após remoção produtor; root inválido/nonobject rejeita antes DB; imports duplicados ambiguous.
Runtime RecordingLLM: oito etapas/log duplo, persistência/isolamento; falhas LLM uma chamada sem retry e index mantém fonte; corpus local sem inferência; intenção inválida auditada; preferência atual antes modelo e assistant text não aprendido; confirmação sem LLM.
Scoped preferences clock2030 controlado: turn>session>project>user, remoção fallback; endereços exatos, expiração UTC após reopen e sem mutar revision; scope/expiry inválidos sem writes; tombstones/provenance/rebuild; legacy tabela migração sem reescrever JSON; transação rollback e stale rejection.
Selection procedure subprocesso start/resume/checkpoint sem repetir efeitos/modelo; missing pointer impede verification; offline audit boundary bloqueia socket e escrita externa em filho. Não prova sandbox universal do sistema.
System expansion: SummaryAgent texto curto preserva literalmente negação/prazo sem modelo; historian grandes JSON relevantes identidade Unicode; policy recheck e oversized indivisible abstain, quote fora recorte rejeitado.
Context budget UTF8+JSON: defaults2000 bytes, prefs intactas, history truncation indicada, auditoria separada/retida; perfil essencial maior rejeita sem truncar; char bound legacy e scopes isolados.
Review fixes threading events: delayed missing read não sobrescreve perfil recém criado; trigger snapshot rollback criação; turn_id igual decision e prefs temporárias/feedback/history; profile leitura não cria/reassign sessão alheia.
Workspace API CaptureModel: upload path não confiável descartado, hash/dedupe/reopen, tamanho UTF8/extensions; search projeto exclusivo sem modelo; feedback owned/reason não treina prefs; perfil deterministic; origens maliciosas/Host rejeitados antes persistência, CSP/nosniff.
Verified fields lookup sem LLM estado/trial/ausentes; interpretações continuam unverified geração; identidade exata sample não migra vizinho; versões conflitantes preservadas; API job literal completo zero chamadas; revogação impede resolução e condições/unidades íntegras.
Bundle remediation fixture: unauthorized guess indistinguishable sem SQL entities/reservations; approval reservation antes membership; verify revogado antes CAS; external relation não concede papel; descriptor revision resolve; fsync failure no commit; raw variants quota/integrity/backup; evidência metadata sem CAS; conflitos administrativos concorrentes atomic.
Hypothesis catalog temp produtor: spans JSON/JSONL literais, chunks exaustivos, source clocks não adivinhados; Git revision mock fixture; duplicate import/drift/newrevision, output fora produtor; duplicatas/não finite rejeita antes publicação, grande objeto JSON indivisível.
Packaged resources byte SHA original=package, loaders default data_root e source identity não vazia/commitNone.
Project coverage snapshot/bundle contagens separadas e repository not_established/workflow snapshots_only; revogação scope/role; corruption não empty; CLI/API; input drift hash e clocks/receipt time não currenttruth.
Research bundle fixture pré-aprova synthetic entity/artifact15bytes: CAS dedupe/offline materialize, scopes/revocation/caps/reference no fetch; hash/truncation/missing corruption; projection rebuild; injectedDB fail orphan/reencontro; concurrent1admitted1duplicate; junction; backup modes/tamper; metadata-only historian etémero DERIVED; childos._exit promoção/projeção e ENOSPC. Legacy gitshow baseline skip se shallow.
Structural diagnostics: restart idempotência, generate/role revocation, scope denial, payload tamper campos actor/scope/assertion/id reject; mock total51 demonstra paginação mesma transação, não 51 bundles reais.
Agent evidence routing dublês: operação solicitada versus material citado, intenção explícita evita classifier; ambiguous clarification; classifier JSON invalid falha1call; context autorizado intacto; SearchAgent evidence real corpus+citações pós geração, marker inventado bloqueado; nohit0call; isolamento/current/prefs; budget2400char e fonte precede memória, não semantic truth.
Arithmetic sequences frações/negativos/decimais cinco casos determinísticos; ação misturada/código/ambiguidade recusada; divisão zero/número enorme limites explícitos.
Embeddings FakeOpener: batches2+1 truncatefalse normalize, NaN/zero/types/dims recusados1call; inputguard0call; cache hash/reopen/digest/text invalidation e corrupção/dimchange fail, sem avaliar embedding real.
Explicit preference pureadapter: NFC/valores canônicos, quotes/docs/thirdparty/ambiguidade não aprende; correção última vence personalidade fixa; negation remove matching sem inferir opposite, tombstones; assistant/transcript notlearning; pastedbody não prefs.
Functional generation controls dataclass serialization conserva think/ctx/predict/bytes/timeout na instancia Ollama, nenhuma inferência.
Hybrid search vetores injetados fabricam similaridade: lexical nohit+semanticmatch; identificador exato vence score maior vizinho; tie sorting estável; arquivo edit/hash/cache refreshed; scopes/offsets/hashes/clipping; falha embedding não fallback. Não valida semântica dos embeddings reais.
Literal command route conversa por instrução explícita inteira; vazio clarification, comando citado não override busca. Testa rota, não fidelidade de geração.
Literal JSON schema chaves limitadas/escaped/unicode, ambiguidades/depth recusados; tipo explícito sem constvalue; Model estruturado uma chamada/originaloutput sem retry, não semântica dos valores.
LLM fixtureHTTP loopback socket real backend simulado: Fake marcado/determinístico; /api/generate body/options; oversized antes request; erro503/missing/partial1call sem fake fallback. Não servidor Ollama real.
Preference scopes marcações explícitas/localized e negação extraída; untrusted quotes/docs excluídos; pureadapter scoped exigeIdentityService e striprouting mantém tarefa.
Provider composition AST proíbe import cli factory em dois arquivos, fake config instanciado sem modelo. Restrição sintática específica não prova arquitetura completa.
Recording provider tool import, isinstance Ollama e model_identity HTTP resposta mock conserva digest/ctx/think. Digest real-digest é fixture literal, não verificação modelo instalado.
Routing identity prioridade keyword versus explicit auditada; feedback não atribuído preserva fonte sem treino; contexto só usuário proprietário.
Search providers tempdocs/serverloopback: leitura bounded/HTML strip; private IP/credentials blocked; redirects revalidated DNS pinned via socket mocks; errors/size/nontext sem retry; AutoRetriever web failure nunca vira localhit. Não internet real.
Streaming BytesIO mockNDJSON incremental provisional→done/metadata, falta terminal/truncation/error nunca done; localbudget/NDJSON validation; close libera stream; PIL importorskip imagens e base64/pixel limits, forwarding. Não multimodal quality.
CLI chat stdin simulado session preference mantém global e reabre session exata, literal resumo sem LLM.
Evidence byte budget serializedUTF8 inclui idioma/instruções e reserve ctx; Unicode/escaping labels clipping auditado hashes/offsets; lowerrankomit counts, fixedinput oversize0retrieval0generation; fallback legacy chars declarado sem byteattr.
LLM contract mockurlopen: schema/options/think/timeout forward, plain sem format; malJSON/invalidschema/truncationmetadata/resetfailure/inputUTF8/reserve guard explícitos uma chamada, sem servidor real.'''.splitlines()
rows=[r for r in json.loads(study.read('cain-shared',study.ROOT/'evidencias/cain/source-index.json')) if r['path'].startswith('tests/')]
assert len(rows)==len(notes),(len(rows),len(notes))
out=[]
for r,n in zip(rows,notes):
 s=study.read('cain-shared',pathlib.Path('C:/CAIN/projeto')/r['path'])
 out.append(dict(path=r['path'],sha256=hashlib.sha256(s.encode()).hexdigest(),review='integral-semantic-read',notes=n,execution='not-executed-in-this-study',tests=[x.name for x in ast.walk(ast.parse(s)) if isinstance(x,(ast.FunctionDef,ast.AsyncFunctionDef)) and x.name.startswith('test_')]))
extra=[]
for p in ['.ci/cain-supply/test_posix_gate.py','.ci/completion/test_posix_gate.py']:
 s=study.read('cain-shared',pathlib.Path('C:/CAIN/projeto')/p)
 extra.append(dict(path=p,sha256=hashlib.sha256(s.encode()).hexdigest(),review='integral-semantic-read',notes='POSIX ordinaryLinux explicitassert/euid; unsafe nodes FIFO/symlink, dirswap TOCTOU, permission revoked before CAS, unreadableblob, injection7durabilitypoints, actual syscall ordering fsync/link/COMMIT with trace, source mutation/delete duringtransfer and hardlinkcopyindependence. Requires CAIN_CANDIDATE_ROOT; not executed Windows.',execution='not-executed-in-this-study'))
out+=extra
study.save('evidencias/cain/shared-test-notes.json',out)
study.save('evidencias/cain/shared-test-coverage.json',[{k:r[k] for k in ('path','sha256','review','execution')} for r in out])
study.save('evidencias/cain/shared-test-review.md','# Revisão semântica dos testes CAIN\n\n67 arquivos revisados integralmente, 65 em tests e dois POSIX .ci. Fixtures, doubles, assertions, subprocessos e skips foram examinados; nenhum teste executado neste estudo. Hash abaixo é conteúdo UTF8 lido, manifesto original preserva bytes físicos.\n\n'+'\n\n'.join('## '+r['path']+'\n\n'+r['notes']+'\n\nSHA256 conteúdo: '+r['sha256'] for r in out)+'\n\nLimite comum: doubles, JSON fixtures e servidores de teste validam contratos de engenharia; não demonstram qualidade de modelos reais nem conclusões científicas/econômicas. Testes declarados não equivalem a testes aprovados. Dois POSIX devem ser conferidos por igualdade de hash.\n')
study.log('cain-shared',study.ROOT,'Revisão semântica manual de todos 67 arquivos de teste identificados; notes+coverage separados',0,'67 semanticamente revisados; execução não realizada',artifacts='cain/shared-test-notes.json cain/shared-test-coverage.json cain/shared-test-review.md')
print(len(out),'semantic reviews',extra[0]['sha256']==extra[1]['sha256'])
