from crypto_tests_record import record
record('16',{
150:'CostModel algebraico: duas pernas fee/slippage em posição absoluta, funding long paga/short recebe e linear24h, net .0069, zero posição sem custo e edge pequeno líquido negativo. Parâmetros são declarados, sem calibração histórica.',
151:'Crowding log OI/(volume*spot) em fixtures, alinhamento mais recente anterior à decisão, futuro excluído e tolerância; ausentes/zero neutro e tolerância negativa erro. Nome diz negativo mas body apenas volume zero, portanto negativo não demonstrado aqui.',
152:'Funding/OI fixtures transformados em SignalPoints enriched com hash64 e três métricas; SQLite persiste três pontos, scorecard DEGRADED e COLLECTION_ONLY. Timestamp de ingestão artificial; sem API/qualidade externa.',
153:'Filtro opt-in defaultFalse preservado, mínimo20 da mesma constante calibrada; custos .003 convertem .002 em NO_TRADE e retorno grande apenas SHADOW_TRADE com capitalFalse. Sem calibration retorna failclosed; fundingNaN rejeita. Constantes não provam edge econômico.',
154:'Prefix regression compara todos campos asdict com inputs efetivamente truncados em três cortes; perturba fortemente rates/OI/spot futuros e mantém prefixo. OI futuro não preenche missing; candle fechado ausente não é bridged e volume futuro não altera crowding. Evidência causal sintética, não integridade vintage de provider.',
155:'HMM stub fixo + série seeded compara cada posterior/estado em prefixos50/120/199 com completo; contraprova backward smoothing muda passado e dá sensibilidade. Modelo real treinado só primeiros150 também compara prefixo220, mas importorskip numpy/hmmlearn/sklearn. Sem qualidade preditiva ou treinamento em mercado real.',
156:'230 dias CSV sintético sinusoidal/funding spikes, DXY published_at dia seguinte e calendário assumido disponível na origem. WFA integrado cobre folds/artifact com final UNVALIDATED e diagnostic GO/NO-GO, missing DXY argumento erro. Primeiro teste nome comportamento inalterado apenas exige n_folds>=1, não compara saídas com referência. Módulo skip sem hmmlearn/sklearn.',
157:'Macro dummy usa assume_calendar_known=True; DXY retorna % com defasagem declarada businessdays, exclui futuro e sexta até segunda, CSV inválido/vazio falha e coverage imputed. Lag0 admite close do mesmo dia, teste não prova hora de publicação. Segunda7Set feriado é aceita: calendário é de weekdays, sem prova de feriados/vintage real.',
158:'Paper report composto, closest price de candle fechado e tolerância, n_active/n_flat; PnL .1 usa preços fake100->110/exists patch e marca retrospective_records1. max_ddNone com um trade. Não observa fills, custos reais ou forward performance.',
159:'Importorskip hmmlearn em helpers: latest_signal max timestamp, ref_price candle fechado/tolerância e futuro rejeitado. position_math apenas calcula expressão direction*strength*kelly no próprio teste, sem invocar produção; default Kelly=.5 prova constante, não homologação econômica.',
160:'Equity slots sintéticos concorrentes perdas aditivas, ganhos realizados reinvestidos, slot ocioso sem rendimento e curva não negativa; Sortino/Calmar convenções (zero sem losses, Calmar cumulative/DD). Não exercita seleção de trades ou capital real.',
})
