import study,json
r=study.ROOT
terms=[
('OD / DD / ET-SRC / ET-HIST / ET-RUN / EU / INF / NV','Categorias deste estudo: observado, declarado, teste fonte, resultado histórico, teste executado, uso, inferência, não verificado.','Mandato seção3; REGISTRO.log'),
('HEAD / origin/main local / main remoto','Commit checkout, ref remote-tracking e ref consultada no servidor, respectivamente; não são intercambiáveis.','evidencias/*/baseline.json; git rev-parse e ls-remote'),
('DatasetFreeze','Contrato de congelamento: hashes, partições, cutoff e proveniência declarados, sem provar qualidade econômica dos dados.','core: src/predictor_core/contracts/scientific.py'),
('PastView / ReplayEngine','Visibilidade de prefixo histórico ao handler, validando ordem/disponibilidade; referências/ambiente não sandboxados.','core: src/predictor_core/measurement/replay.py'),
('TrialRegistry / TrialRegistryV2','Registro V1 com lock e superseded; V2 prospectivo com validação própria, sem herdar lock V1. Versão do registro não é protocolo ResearchV2.','core: measurement/trials.py; contracts/trial_v2.py'),
('Brier / RPS / DM / PSR','Métricas probabilísticas, comparação Diebold-Mariano e probabilistic Sharpe ratio; validade depende amostra e premissas.','core: measurement/metrics.py; stats.py'),
('PIT / available_at / cutoff','Dado admissível pela sua disponibilidade antes da decisão, não apenas data do evento; a implementação varia por domínio.','core: data/contracts.py; Brasil research_runtime temporal; Stocks cvm_pit.py'),
('Ops run / provenance / heartbeat','Execução subprocesso com lock, tentativas, timeout, registros e vida; êxito operacional não decisão científica/econômica.','ops: src/predictor_ops/runner.py; provenance.py; CLI (ver inventário)'),
('predictor.plugins','Entry point de capabilities/contratos com import opcional; não prova disponibilidade de inferência ou um serviço central.','pyproject.toml de domínios; ecosystem registry'),
('ResearchSnapshotV1','Publicação documental com origin, records, evidence, coverage e restrictions; ID sela conteúdo canônico.','ecosystem: packages/research-snapshot/src/research_snapshot/contract.json'),
('ResearchBundleV1 / CAS','Entidades/relações/artefatos; content-addressed storage pelos hashes, com objetos recebidos distintos de referências.','ecosystem research-bundle/contract.json; CAIN research/{bundles,objects}.py'),
('ResearchTaskV1 / ResearchResultV1 / AuthEnvelope','Mensagens de pesquisa autenticadas no protocolo examinado, com assinatura e validade; distintos dos exports documentais.','ecosystem: packages/research-protocol; Crypto research_{admission,results}.py'),
('Research envelope V2','Papel declarado no Anexo; não demonstrado nas fontes primárias estudadas. evaluation/v2 CAIN é avaliação do produto e não esse envelope.','DD AnexoA2/A3; fontes primárias protocol1.0.3rc1 e src/cain/evaluation/v2.py'),
('Scope / grant / binding','Escopo usuário/projeto/coleção, permissões e raízes de importação que delimitam leitura/geração; reautorização em query.','CAIN: src/cain/research/service.py; bundles.py'),
('Received / referenced','Bytes recebidos e verificáveis versus referência cujo conteúdo não foi admitido; arquivo citado não amplia coverage.','Snapshot/Bundle contracts; CAIN inspection.py'),
('Proposta / semantic_support','Texto de IA e citações estruturalmente aceitos; não certifica suporte semântico ou verdade factual.','CAIN research/analysis.py; field_review.py; evaluation/quality.py'),
('Workflow checkpoint','Sequência durável, retomada e aprovação explícita de geração; cancelamento/completed pertencem ao job, não à ciência.','CAIN src/cain/research/workflows.py'),
('DESCRIPTIVE_REPLAY / WFA','Reutilização de fit histórico descritivo versus divisão walk-forward separada; causalidade da inferência não corrige fit futuro.','Crypto GarimpoInvestimentos/v3/{pipeline,regime_engine}.py'),
('SHADOW_TRADE / SHADOW_CANDIDATE / FORBIDDEN','Estados de observação e vedação; não tratar candidato como operação autorizada.','Crypto core/economic_gate.py; Brasil recommendation.py; plugin.py'),
('CLV / closing_definition','Comparação com cotação de fechamento sob definição/time/book; alternativaBrasil sem offer aceita pode declarar NOT_MEASURABLE.','Brasil temporal/prospective_shadow.py; pesquisa alternativa handler'),
('H8 / H9 / H14 / H15 / A1','Identificadores de hipóteses do domínio Brasil, com proteção e tipos próprios; mesmo número H em outro projeto não é identidade comum.','Brasil plugin.py; research_runtime/handlers; A1 arquivos no inventário'),
('H4 / H6 e CLAIM-BR-MARKET','IDs de relatos usados por CAIN como identidades fornecidas pelo domínio; não prova validade da hipótese.','CAIN research/historian.py e evaluation protocolos; exportadores domínio'),
('DT_RECEB / D+1','Disponibilidade de documentos CVM deslocada para dia seguinte; dataevento e datarecepção distintas.','Stocks stocks_predictor/cvm_pit.py; ingest_cvm.py'),
('RJ episodes / repeated companies','Episódios de recuperação judicial com scores próprios; episódios sobre mesmaempresa afetam independência.','Stocks rj_episodes.py; rj_judge.py; rj_models.py'),
('R6 / R7 / R8','Receipts/consolidação/lacre operacionais próprios Stocks, com verificadores CI; não gates de rentabilidade.','Stocks .github/workflows/ci.yml; tools/{audit_registry,verify_operational_evidence}.py'),
('Gate / finding / P0 / P1 / P2','Resultado e artefato de verificação versus problema e impacto. Prioridade não probabilidade/certeza.','qualification/crypto/GATES.json; FINDINGS.json; scripts/attest.py'),
('C7.1 / QUALIFIED / NOT_QUALIFIED / IN_PROGRESS','Regras e estados de atestação vinculados a baseline e missão; check implementa subconjunto e não transfere decisão a novo commit.','qualification/COMMON_QUALIFICATION_CORE.md; scripts/attest.py; attestation-epochs.json'),
('D-27 / D-29 / D-30 / D-31','Decisões descritas pelo dono para outra época; conteúdo/aprovação atual NV nas fontes primárias anteriores.','DD AnexoA3/A5; qualification/DECISIONS.json local analisado'),
('Cleanroom / ET-HIST','Instalações de wheelpublicada e buildHEAD isoladas, com introspecção; logs históricos precisam commit/ambiente.','qualification/shared/scripts/cleanroom_baseline.py; RAW_LOGS catalogados'),
('Edge / capital_allowed','Alegação científica/econômica e permissão de capital requerem evidência distinta; smoke, bootstrap ou gate não bastam.','Charters/economic_decision domínio; contratos Core; docs de cada projeto')]
study.save('relatorios/docs/GLOSSARIO.md','# Glossário com origem\n\nOs nomes de arquivo são relativos à raiz do projeto indicado. IDs têm namespace do domínio; V2 em módulo de avaliação não é automaticamente envelopeV2.\n\n|Termo|Significado e limite|Origem observada ou DD explícita|\n|---|---|---|\n'+'\n'.join('|'+a+'|'+b+'|'+c+'|' for a,b,c in terms)+'\n')
orders={
'cain':['pyproject.toml e settings.py','runtime.py → orchestrator/routing.py → agents/','workspace.py e persistence/adapters/sqlite.py','research/service.py → bundles.py → objects.py','research/grounding.py → historian.py → analysis.py → workflows.py','api.py/research/api.py e web/app.js; mcp.py','llm/ e providers.py; evaluation/ e testes correspondentes'],
'cripto-predictor':['pyproject.toml → uv.lock → plugin.py','GarimpoInvestimentos/config.py e governance.py','dpl/feature_store.py e ingestion.py','research_admission.py → research_execution.py → research_worker.py → research_results.py','core/economic_gate.py; trials.py e v3/pipeline.py','packages/research-export/; workflows CI e tests'],
'brasileirao-predictor':['pyproject.toml → uv.lock → plugin.py','CLI e config apontados source-index','data/ e temporal/ bitemporal/prospective_shadow','backtest_event.py e event_models.py','economic_decision.py → recommendation.py/calibration_gate.py','tools/export_cain_* e testes; suplemento research_runtime da outra época'],
'stocks-predictor':['pyproject.toml → uv.lock → main.py','db.py → ingest_cotahist.py / ingest_cvm.py','cvm_pit.py → factors.py / factor.py','backtest.py → simulation.py → profit_validation.py','rj_episodes.py → rj_judge.py; etf_hold.py; discovery/','external_intelligence.py → diagnostics.py → tools/verify_operational_evidence.py','tests por responsabilidade; CI e export_cain ferramentas'],
'core-predictor':['pyproject.toml e __init__.py','contracts/scientific.py e data/contracts.py','measurement/replay.py → metrics.py → bootstrap.py','measurement/trials.py e contracts/trial_v2.py','data/router.py → circuit_breaker.py → source_quality.py','kernel/ persistência/net e testes leaf/contratos; tools/check_installed_wheel.py'],
'predictor-ops':['pyproject.toml → src/predictor_ops/cli.py','runner.py e callbacks do runner','lock/heartbeat/mutation_guard e timeout','provenance.py e receipt schema','tests runner/recovery/concurrency; CI installedwheel; suplemento Windows4.2.2rc1'],
'ecosystem-predictor':['pyproject.toml → src/ecosystem_predictor/contracts.py e registry.py','packages/research-snapshot contrato+validador','packages/research-bundle contrato+files','packages/research-protocol messages/auth','registries arquitetura/compat; compat/locks e CI','scripts/check_ecosystem_drift.py e tests; versões V2/transport do AnexoNV'],
'predictor-qualification':['qualification/COMMON_QUALIFICATION_CORE.md como DD e regras','shared/scripts/collect_stack_baseline.py → cleanroom_baseline.py','crypto/scripts/attest.py → evidence_numbers.py','GATES/FINDINGS/schema e atestados de época','crypto/scripts/e2e_runtime.py → science_real.py → soak.py','workflows e RAW_LOGS somente correspondentes ao SHA/gate investigado']}
text='# Guia de leitura\n\nComece por LINHA_DE_BASE.md e RELATORIO_GERAL.md; depois PRELIMINAR, INVENTARIO e COMO_FUNCIONA de um projeto. Cada path abaixo deve ser confirmado no source-index/source-catalog: alguns itens agrupam nomes para orientar módulos, não são comandos. A cobertura informa onde há aprofundamento pendente.\n\n'
for p,seq in orders.items():text+='## '+p+'\n\n'+'\n'.join(str(i+1)+'. '+x for i,x in enumerate(seq))+'\n\n'
text+='Na primeira passagem, ignore caches, wheels, ambientes e datasetsbrutos; catalogue relatóriosdatados/RAW_LOGS sem lê-los como verdade atual. Volte a eles somente para o gate ou conclusão em disputa. Não execute exemplos/doctor/verificadores no original: diversos inicializam bancos ou gravam recibos. Leia o preflight e a saída de ET-RUN antes usar os resultados.\n'
study.save('relatorios/docs/GUIA_DE_LEITURA.md',text);study.log('APRENDIZADO',r,'Glossário com namespace/origem e guia ordenado de oito projetos',0,str(len(terms))+' termos',artifacts='relatorios/docs/GLOSSARIO.md; relatorios/docs/GUIA_DE_LEITURA.md')
