from shared_brasil_scripts_record import record
record({
'brasileirao_scripts/register_retest_2023_2026.py': 'Consome resultado externo RETEST e sharpes observados, produz controles sintéticos seed13/14 para attest_pipeline_power, registra H8 train2023–25/test2026 com stake1 shadow e valida registro. Notas reconhecem observação anterior ao registro e preços pós-jogo aproximados: não confirmatório; capitalFalse. Arquivo consumido não tem hash validado por este runner; análise DSR depende PnL fornecido.',
'brasileirao_scripts/registrar_h5.py': 'Registro H5 ensemble pesos fixos e parâmetros xG/cosh, shadow0u; gate100 e CI CLV/ROI descritos em notas, métricas históricas alegadas no texto não recalculadas aqui. Não emite atestação própria nesta função; dependências do wrapper/registros existentes determinam validação. Registra e imprime lista completa, sem experimento nem autorização de capital.',
'brasileirao_scripts/renew_core3_harness.py': 'Executa harness RPS sintético, descreve geradores N300/skill/seeds e SHA da descrição, não bytes de dataset. Atualiza atestação companheira via tmp.replace; labels controles COMPROVADA/REFUTADA são literais após helper validar. Nome temporário compartilhado sem lock; atestação do pipeline sintético não prova modelo esportivo nem lucro.',
'brasileirao_scripts/replay_round_2026_08_22.py': 'Replay 10 IDs fixos: DB SQLite RO, consulta Sofascore HTTP sem cache para resultados; calibração/histórico anteriores ao dia e Elo temporal. Snapshot escolhido por captured_at pré-KO, sem bookmaker/source/vintage verificados; nenhum receipt de execução. EV>=5% e PnL bruto unitário, report explicitamente CONTAMINATED/capitalFalse, manifesto hashes DB/config/script. Limitação n=3 literal pode divergir dados; capturado ausente pode causar erro e conexão não fecha explicitamente.',
'brasileirao_scripts/report_h9_execution_quality.py': 'JSONL estrito sintaticamente; primeira linha EMITTED por event_id prevalece, senão última por ordem do arquivo. Taxas/slippage são proxies dos campos, sem recibo de fill; ignora linhas sem event_id e não valida finitude/assinatura/tipos. Identidade event_id difere sofascore_event_id de missed_windows, podendo separar universos.',
'brasileirao_scripts/report_h9_missed_windows.py': 'Consulta fixtures KO>=since em DB RO fechado finally; função finished não filtra estado finished. Qualquer tentativa por sofascore_event_id elimina alerta independentemente timestamp/status: tentativa fora da janela pode ocultar perda. Janela KO-horizon-15min até KO, grace20min; malformed KO pulado. Alerta pós-KO retorna exit0: sucesso do job não implica janela coberta.',
'brasileirao_scripts/report_shadow_mode.py': 'Dedup primeira linha por (event_id,selection), sem contrato/book/source na chave. predicted_at fallback captured; valida predicted<KO quando existe, mas não received/captured pré-KO; sem KO aceita ordem por data e same-day marca indisponibilidade. Settled>=captured, não necessariamente KO; merge result sobrescreve campos pick. Métricas aceitam bool e não validam finitude/bounds; ROI média PnL pressupõe unidade, ESS=n cru, bootstrap IID2000 não clusters, DD aditivo. Sempre INCONCLUSIVO com dados (até n>=100); sem dados insuficiente. --db é só proveniência. Saída JSON overwrite permite NaN.',
'brasileirao_scripts/research_01a_refit_cadence.py': 'Controle retrain100 tratamento10, default2021–24; holdout2025 exige unseal. Emparelha listas date/home/away, compara4losses com movingblock bootstrap e guardrails; contrato somente primeira linha. CI cruzando0 vira REFUTADA, não inconclusivo; CI inexistente pode falhar formatação. Harness RPS sintético vs uniforme N300 produz companion/prereg antes carga, pre-register-only ainda escreve atestação. cfg carregada não passada ao _arm. Não prova WFA inteira, fonte vintage ou economia; reporte sobrescreve artefato sem manifesto completo.',
'brasileirao_scripts/research_dynamic_strength.py': 'Compara serving/dynamic_strength períodos development2021–23, validation2024 ou diagnostic2026; igualdade ordenada chaves impede despareamento. Losses por jogo e CI bootstrap do benchmark, coverage=1 literal após filtro; vazio divide por zero. Accuracy diagnostic_only; sem registry/atestação, recibo de congelamento ou hashes fonte neste runner. Janela temporal do motor não prova publicação PIT.',
'brasileirao_scripts/research_market02_1x2.py': 'Residual multinomial l2=5 usa diferenças log-odds serving/opening Shin: expansão development depois300 em blocos100 e modelo congelado em todo dev para2024. Exclui jogos sem opening, closing só referência subconjunto. Coverage dev denominador já dev_test exclui missing opening e primeiros300, portanto1 não cobertura universo. Inputs opening legacy não comprovam PIT; odds não valida NaN explicitamente; empty train/validation sem guard. CapitalFalse/holdout2025 e2026 não carregados.',
'brasileirao_scripts/research_market_0b_resolution.py': 'Precheck development2021–23 controla carga validation2024: só PROCEED_TO_FULL_0B abre nova carga. OU25/BTTS permutation1000 seeds distintos, potência referência dev. Sinal se qualquer braço validation sinalizar, sem ajuste entre mercados explícito no runner (helper pode aplicar interno). Retrospective_read_only/economic_eligibleFalse/capitalFalse; valida permutations>=1 e escreve overwrite.',
'brasileirao_scripts/research_market_edge_ordering.py': 'Development2021–23/validation2024 residual OU legado com sharpes TrialRegistry para DSR no helper. GO sinal depende draw monotonicROI, power mínimo e permutation null<.05, não todos possíveis diagnostics. Source explicitamente agregado sem bookmaker, economicFalse/capitalFalse. JSON allow_nanFalse; permutations>=1. Não toca holdout2025/2026 por limite carga, não prova congelamento prospectivo.',
'brasileirao_scripts/research_ou25_annual_2021_2026.py': 'Always-bet counterfactual escolhe lado maxEV mesmo EV negativo, sem filtro; bruto unitário/CLV devig closing quando presente; preços validados e rejeições contadas. Governed policy literal NO_BET profit0/capitalFalse, não log de execução. Holm6 testes anuais; temporadas2024–26 explicitamente contaminadas, 2026 as_of literal2026-08-27 não limita load_rows sem cutoff. Manifesto DB/backfill/runner/artifacts, não todas dependências; hash pós-leitura não isolamento snapshot.',
'brasileirao_scripts/research_ou25_certainty.py': 'Avalia sports e market anchored (past-only helper), treino190/bloco38, início560. Policy eligible n>=200 ROI_CI_lower>0 Holm<=.05; summary GO se qualquer braço, capitalFalse/scorecap40. Holm por resultado helper não ajuste explícito entre2arms. Backfill legacy e retrospecção não prospectiva; só hash artefato por braço, sem manifesto DB/config próprio.',
'brasileirao_scripts/research_ou25_factorial.py': '9 células retrain10/20/100 × outerblock38/95/190, nested grid inteira reportada sem escolher vencedor; minimumtrain560 seedfixa. Summary retrospective contaminated/prospectiveFalse/capitalFalse/score40. Hash resultado por célula, sem manifesto fonte total e sem ajuste inter-células explícito; matriz não comprova retorno executável.',
'brasileirao_scripts/research_ou25_market_anchor.py': 'Anchoring prequential190/bloco38 seguido nested replay mínimo560/bloco95. Verdict NO_GO n<200, REVIEW_REQUIRED caso contrário independentemente ROI/CI: tamanho sozinho não libera capital. CapitalFalse/score40; hashes2artefatos, sem manifesto completo; fonte backfill retrospecção.',
'brasileirao_scripts/research_ou25_nested_replay.py': 'Grid1620 combinações edge6×max3×odd5×side3×q3×friction2; load_rows exige DB e backfill existente/não vazio, mas usa aggregate backfill por event_id ou fallback market_open/closing legado sem captured/bookmaker; existência não valida PIT. _load_observations sem cutoff inclui todos dados disponíveis. Conexão preço RO; CLI mkdir antes validação, sem bounds retrain/mintrain/block. Nested helper grava frozen candidate e perdas; manifesto source/runner/HEAD/DB/backfill/grid/artifacts, mas HEAD não cobre dirty nem dependências, hashes posterior não snapshot isolamento. CapitalFalse e preço retrospectivo; frase preço executável em erro não comprova executabilidade.',
'brasileirao_scripts/research_residual_diagnostics.py': 'Carrega até2026 e diagnostica OU dev2021–23, T2 2026, equipes e market2021–24; modelos/mercado são comparação retrospectiva. T2 usa intervalo binomial p=.5 e normalCI lambda, classifica RESULT_NOISE se zero incluído: ausência de sinal não prova ausência drift. n<2 stdev/mean pode falhar. Mercado ausente é zero em bins e resolução mas perdas excluem missing, universos diferem. MDE aproximado odds1.9 n380 artificial; triagem Shan/Power não valida prospectiva. LOCKED literal; sem hashmanifesto, NaN defaultpermitido.'
})
