from shared_brasil_record import record
record({
'tests/test_elo_baseline.py':'40 jogos planted forte/fraco: properdistributions/strengthfavored/determinismo/drawrateinterior. Não marketaccuracy; drawrateassert não verifica valor do truncamento.',
'tests/test_elo_baseline_block_guard.py':'40blocks fixtures simultâneos contabilizam blocked>0, horáriosdistintos0; semhistoryusable lançaerro, predicted<matures e normalização. Nome drawrate from truncated só bounds0..1, não contraprova futuro.',
'tests/test_emit_h9_shadow.py':'SQLite Elo/cache e trials modelo fixtures, approved_bookmaker monkeypatch permite shadowwindow; emitscapitalFalse/currentElo/fingerprint16, frozenparams usados, cacheold fail e idempotência. Missingquote/team/wrongbook/block são auditados. Campo executed_odds é odd da cotação shadow e slippagevsbest meradiferença preçosfake, não execução real.',
'tests/test_evaluate_h14_prospective.py':'3 vs21 eventos com probabilidades fabricadas: mínimo antes métricas, n21 gera verdictenum/capitalFalse, unknownoutcomeexcluído e CLI refuseoverwrite. Não comprova timestamps prospectivos nos fixtures (ledger mínimo sem predicted_at) nem autenticidade.',
'tests/test_evaluate_h15_prospective.py':'Mesma estrutura mínimo21/refit10 vs100 declarados, n3 espera, n21 calcula, missingoutcomeexclui e overwritefailure. Não reestima modelos ou afirma beneficio refit real.',
'tests/test_exp001_coverage_audit.py':'Dois eventos porhorizonte um missing mantém denominatorcoverage.5; não coverage observada.',
'tests/test_exp001_cutoff_state_regression.py':'Timelinefake latestinactive/partialleg/unknownactive/tieconflicts impedemressuscitação, futurestateignored e reactivation antescutoff aceita. Transporterrorsrequests monkeypatch traceback sem keyURL. Sem请求 API real ou sourcevintage autenticada.',
'tests/test_exp001_data_pilot.py':'1x2 timelinefixture futuroprice99 excluído e missinglegs failclosed; não ingestreal.',
'tests/test_feature_builder.py':'SQLite sintético médias2.25xG/56.5possession antesalvo; ausênciaNone/count0 nãozero, deltaapenasduaslados, side/ALLperiod filtre98/99contaminação. Não verifica published/ingested nesta baselegacy.',
'tests/test_find_odds.py':'Lookupcanon/countryaliases e mandoswap1x2/OUinvariant, closestdate±3dias/malformedignore. Matching aproximado aceita cotação até3dias depois da dataalvo; teste não prova PIT ou identidadeeventid exata.',
'tests/test_followup_capture_contract.py':'Collector/auditor docsreprodução com clock/opener/helper fake: account/odds/account só1metered/idempotente, janelaantescredencial/quota20/paidplanblock, HTTP429semretry/redaction, rawJSONbadpreservado e offlineauditreject. Fixture/hashendpoint/timestamps/admissionprospectivefalseexec. Auditor adda udithook patchdesliga isolamento durante teste, não prova sandbox real. Sem rede/charge efetivo.',
'tests/test_formal_prediction.py':'Aliases fixtures identidade/data/quoteeventwrong reject, model spy blockedbeforecall capitalTrue; formalpredictionid desambigua repeatedmatches e missingref não gravaresultado. Context ready declarativo não atestavintage.',
'tests/test_h10_fadiga_walkforward.py':'Seeded rows60, restcap/sign/debut/outcomes, WFA paired30/games2blocks e constantsbootstrapgain.1. CLItrials tmp reg/attestation viarealhelpers e idempotente, mincal reduzido10; não proves fatigueedge real ou valida parâmetrosserving.',
'tests/test_h9_missed_window_exit.py':'Reportmock missed2risk1 emits stderralert mas exit0. Consequência: schedulerSUCCEEDED não significa ausência de missedwindows.',
'tests/test_h9_shadow.py':'Shadowapprovedbook none bloqueia; quote1.9fake emit idem, resultados2x1 settlementPnl.9/CLV vs1.8 e settledidem. Nome rejects early-result-and-other-book só exercita earlyresult, nenhum bookmakerdivergente neste corpo. Sem aposta externa.'
})
