from shared_brasil_record import record
record({
'tests/test_bet_log.py':'JSONL tmp adiciona/settle idempotente por bet_id, confronto invertido e datas desambiguadas; HT obrigatório para mercados parciais, ROI/drawdown e flows/reinit banca, duplicate apenas warning. Naive vs aware marca late None. validated por mercado não é validação deste fixture. Capital_gate é warning baseado status string comprovada de JSON sintético, não verifica evidência/autorização; ou15 fora do gate retorna None.',
'tests/test_bitemporal_store.py':'SQLite tmp bitemporal só mostra após published e ingested; revisão mais recente/dedup e clock impossível rejeitado. Source/chater strings declaradas, sem provider real.',
'tests/test_bookmaker_odds.py':'Fixtures de nomes acentos/aliases/ambiguidades, kickoff próximo/placeholder meia-noite e mando invertido; JSONL dedup separa bookmaker/mercado. Closing último pre-kickoff/valid>1/selection. Não observa bookmaker e política tolera placeholder sem hora real.',
'tests/test_bookmaker_stability.py':'Três dias sintéticos com cobertura10 classificam pinnacle stable, cobertura1 insuficiente e matchbook rejeitado. Retr ievaltime usado e três smokes em24h mantêm pending. Critérios heurísticos não medem estabilidade externa.',
'tests/test_bootstrap.py':'Seeded bootstrap média/CI/constante/n1/vazio/determinismo, amostra200 estreita mais que10. Não verifica coverage nominal repetido nem lucro.',
'tests/test_brasileirao_domain.py':'Config real identidade325/seasons e sportkey; quatro clubes sintéticos Elo/modelo com probabilidades normalizadas. Resultado Bahia0x2 declarado fixture, não API real. SQL in-memory sync idempotente/remove orphan adiamento/remarca fixture e exclui passado; HT fraction antescutoff/mínimo60.',
'tests/test_build_data_archive.py':'ZIP sintético preserva bytes/mapas/omissões e verifica restore; recusa hashes ruins/overwrite/exclusion incompleta/extras código/snapshot sem receipt/traversal/windowsNFCcase collisions/nesting budget/code referências com credencial. Snapshot é opaco fakeSQLite, receipt integrity_ok declarado não consultaDB real. Não autentica remotecommit nem descriptografa/protege secrets .env que política permite.',
'tests/test_bundle_h9_evidence.py':'Manifest ledger sintético registra hash real bytes/2rows/commit abc123 e capitalFalse, janelas irrecoverable. Não autentica commit ou conteúdo econômico.',
'tests/test_calibration_gate.py':'Report A10 físico NO_GO e servingFalse; métricas declaradas exigem gainRPS>.002/guardrails, candidate só novo protocolo. Losses/CI subset homewin sintético20boot. Sem reexecução do A10 inteiro.',
'tests/test_capture_decision.py':'Payload/receipt fake SHA gerado prova par condicional EV.08 nunca execution/PnL; latestbad não ressuscita older, NaN/dupJSON/clockties/identity/status recusa, futurereceipt excluída antesparse. CLI artifact tmp e overwrite/incomplete-universe reject. Hash comprova bytes transportados declarados, não origem externa ou preço executável.',
'tests/test_capture_sofascore_event.py':'FakeSofascore/clock injetado comprova boundary anteskickoff estrita, naive rejeita, captureJSONL dedup e post-kickoff não entra odds SQLite. wait jáconfirmed não dorme e kickoff false; semHTTP/lineup verdadeiro.',
'tests/test_ci_current_elo_containment.py':'Guard temp root permite script H14 copiado auditado, rejeita db.load_elo em research/backtest/similarname. Prova scanner destes padrões, não ausência de outras formas de leakage.',
'tests/test_ci_dependency_pins.py':'RegexURLs workflow igual uv sources e filenames no checksum. Não calcula hash download ou observaCI remota.',
'tests/test_ci_nao_suja_a_arvore.py':'git check-ignore esperado em quatro artifactdirs; regex --output destinos cobertos. Não executaCI nem cobre todos caminhos de escrita possíveis.',
'tests/test_closeout_coverage.py':'SQLite fixture intersectioneventids impede300%, emptyN/A e nãoInf. Sem cobertura realprovider.',
'tests/test_closeout_integrity.py':'Bad scores bool/fraction/inf sem mutate; JSONL duplicate/orphan/changedprofit/dupkeys rejeitados. Latestquote unusable/tie abstains, origem/evento/contrato misturados erro; chronologypublished/receipt e readiness types/blank fail. Declarations ready mas pre_match_evidence_eligibleFalse explícito.',
'tests/test_closeout_research_inputs.py':'Shadowstake nonfinite/bounds erro; travel coordinates limites, bool strictsurface, coach integer/vintage e recebimento pósKO rejeitados. Conteúdo geográfico/team causal é fixture, não fonte autenticada.',
'tests/test_closeout_status.py':'Tracked SQLite monkeypatch exige read_only=True e closeconnection. Emit_event e loaders mocked, não verifica filesystempermissions ou modo URI real.',
'tests/test_closing_scenario.py':'Decimal cenário congela escolha sem labels/protected2026 e duplicatas; selfodds nenhumedge, badprices mantémABSTAIN. Principal não luc ro, win1.38/loss-1.02 e unresolvedlockROIundefined. Mesmo dia ganhos não financiam2ª, dia seguinte sim. Liquidação condicional por labels fixtures, não execution/recebimento real.'
})
