from shared_brasil_scripts_record import record
record({
'brasileirao_scripts/permutation_test.py':'CLI WFA controle negativo embaralha pares completos de placares entre datas, sem estratificação. Default3 permutações; passed se nenhum CI superar climatologia. Período2021..2024 e holdout2025 bloqueado salvo explicitunseal. Apenas3 controles não estimam taxa de falso positivo precisa. Escreve relatórios com overwrite e logs detalhados; não executado.',
'brasileirao_scripts/persist_h14_prospective.py':'Trialrequired/load params e cache computed aware <=12h/nofuture, currentElo serve, window24h preKO e ledger dedup event_id; fingerprint16 policy hash sem source/codebytes. Climatology exige rowkickoff<targetKO via strings, não<=decisionnow/publication/receipt. Pode incluir priorfixture iniciado apósnow porém beforetarget com resultado jánaDB. JSONL semlock/strictjson/hash; reschedulemesmoid fica already. DBreadonlyfinallyclose.',
'brasileirao_scripts/persist_h15_prospective.py':'Arms10/100 n_completed cadence com compute/read-onlyDB, statesjson replace sem atomic/lock; state não liga fingerprint/config e retornastateantigo se refitNone, sem agemax/futuretimevalidate. Faz refits antesfiltrar fixtureswindow; ledger dedup event_id appendsem lock. Policyfingerprint16 somente desenho, não codehash; writes state/ledgeroriginais se executado.',
'brasileirao_scripts/playoff_clv.py':'No top-level loadconfig/db.connect default migrante, countsopening/população e backtestopen CLVmean/PnL; target25 declarado sem poweranalysis e strings chamam juizdefinitivo/amostra suficiente. Broadexceptmissingtable vira0, connsemfinallyclose. LegacyWC/playoff narrativa genérica, não evidência economicvalidada.',
'brasileirao_scripts/poc_fadiga.py':'Toplevel DBdefault read/writeconnection e Elohistory; train2010..2023 vs holdout2024..May2026/CopaJunexcluded. Restcenter4cap5 e thetaNB minimize customNLL tau sem normalizerNB/optimizer.successcheck. Fixed train modelo/holdout chronologicalElo e Brier/accuracy print, nonemptyassumed/semCI/registry/lock. Exploratórioconsome2025/2026visto.',
'brasileirao_scripts/predict_first18_2026.py':'TopleveldefaultDB/allcompleted, Elo window é escolhido relativo última data base inteira e first18>=Jan28; goalparams fitbeforeJan28, Elohistorystate porjogo. Prints argmaxhits/sem economiccosts, n0division/rows0index falham. Não formalprospectivecapture, semsourcePIT.',
'brasileirao_scripts/predict_first18_ou_dc.py':'Mesma seleçãofirst18/calibrationpreseason, date+canonicalteam join flat currentodds, OUthreshold.5/DCbestside hitrate. Faltapublished/ingested/bookmaker/source, resultados conhecidos e latestDBwindow governa history. ToplevelDBdefault sem close.',
'brasileirao_scripts/predict_first18_teams.py':'Retrospective first18 calculamodel lambdas chamadasxGF/xGA (model expectedgoals, nãoobservedxG), aggregates perteam attackdefense residual/Brierduplicado2divisor. Currentbasehistorywindow escolhido última datafuture; full importexecutaDB/query.',
'brasileirao_scripts/predict_walkforward_ev.py':'Retrospectivefirst18 parameters fixedpreseason, pergameElo; EVlabel usa modelprob/devigmarketprob-1 em vez executableoddp-1, OU/DC thresholds depois PnLofferedflatodd. Missing5odds excluiuniverse, source/clocks/fees/bankroll ausentes. CurrentDBtop-level e sem prereg não forecast/economicvalidated.',
'brasileirao_scripts/prereg_serving_vs_climatologia.py':'Dryrun print noatt/write. Mainattest_rps_power e TrialRegistry registerfingerprint/startnowmidnight n900nointermediate guardrails/powernumbers notes historicalclaimed. Código não mededescritivos claims nesta chamada; registry can write. Prospectivecohort date midnight pode incluir anteshora da inscrição; qualitymodel explicit separado capital.',
'brasileirao_scripts/prever.py':'CLI neutraldefault, unknownteams suggestions; build readonlycache, full show logs thenrender; periodfractionHThistory else.5 logs requiredRuntimeError failure, observabilitybest-effortexceptpass. Optional mata-mata logisticElo aggregate heuristic não leagueMonteCarlo; evento corners/cardsinformational. Algumas exceptions/SystemExit antescloseconn, no formal_contextinput route nestewrapper.',
'brasileirao_scripts/prospective_readiness.py':'Lê JSONL ignora malformed lines, snapshotsgroupretrievalcommonbooks/stability; APIkeypresence e trialname apenas, h9_can_emit combinação sem registryvalidation/credentialauth/quotePIT. CapitalFalse. Flags readiness metadata não atestações.',
'brasileirao_scripts/prova_mecanismo.py':'TopleveldefaultDB/WC2026 retrospective, fixedmodelpreCup/chronologicalElo, date±3dayflatodds+Shin; compares favorito/azarao/rawfair divs. Conclusion vigNÃOcausa print unconditional independente dados: diagnóstico não prova causalidade. Sem truncationPIT/privacy/economicledger, emptywc/rolemeansfalham.',
'brasileirao_scripts/record_closing_snapshots.py':'DBreadonly fixtures,4hglobalgate(forcebypass) mas loops APIrows matchedcontraTODASfixtures, não sóproximos; dados podem outrasjanelas. Dryrun aindaHTTPpotentialbill; bookmakerenvrequiredskip0. Namedclock/hash/provenancepersist but useslegacyadapter eligibility. Conn nunca close embranches. NenhumHTTPexecutado.',
'brasileirao_scripts/record_h9_closing_snapshots.py':'Read-onlyDBfinallyclose, anyKO<=3h permitsAPI totals todosrows (não filtra fixturewindow). retrieved_at=now antes fetch chamado, potencial representa requesttime em vez completereceipt pelo adapter; persistcollectiononly. SOURCE_UNAVAILABLE retornadict mainexitdefault0, schedulerpodeSUCCEEDED.',
'brasileirao_scripts/record_odds_smoke.py':'Reportonlyread; collectHTTP/persist ledger update-lag usa maisrecente quote max não stalepercenttail, rejected_quotes0coded, events_seen denominadorretainedrows nãofixtureuniverse. Payloadhashfirstbookquote, prints picks0. Providerconfigurederror sanitized contracthelper. Não smokeexecution nesteestudo.',
'brasileirao_scripts/register_h9_prospective.py':'Trialcontractphysical/read existingattestation fingerprint, existingnamevalidateregistry; new paramscapitalFalse/testperiodfixedAug9..Dec2027/metricPSR. Registerwrapperchecksattestation mas não comprova actualregistration beforefirstdecision nesta função; notes prospective nãotimestampassertagainstledger.'
})
