import json, pathlib
import study

DATA = {
'core-predictor': {
'root':r'C:\PREDICTORS\core-predictor','version':'3.2.1',
'purpose':'Biblioteca de contratos científicos, medição estatística, replay temporal e infraestrutura reutilizável. O checkout não é um preditor treinado nem um executor de ordens.',
'components':[
('fachadas','src/predictor_core/__init__.py','__getattr__','Exportações lazy; versão obtida de importlib.metadata; import da raiz requer distribuição instalada.'),
('contratos','src/predictor_core/contracts/scientific.py','DatasetFreeze','Charter, SLA, recursos e congelamento com hash; validação estrutural e temporal de metadados.'),
('dados','src/predictor_core/data/contracts.py','PredictionPoint','OHLCV, sinal com proveniência e previsão; providers abstratos; não busca dados por si.'),
('roteadores','src/predictor_core/data/router.py','FallbackRouter','Fallback sequencial aceita retorno sem exceção inclusive lista vazia; AggregationRouter consulta em paralelo e exige sobreviventes não vazios, aplica mediana/média por timestamp.'),
('circuito','src/predictor_core/data/circuit_breaker.py','CircuitBreaker','Closed/open/half_open com contador e monotonic clock; libera uma probe e emite evento nas transições.'),
('qualidade','src/predictor_core/data/source_quality.py','source_quality_scorecard','Coverage/freshness/gaps/revisions/availability/divergence; causality/integrity violadas levam QUARANTINED. Freshness calcula ingested-published, não idade atual do dado.'),
('ajustes','src/predictor_core/data/quality.py','infer_split_factor','Heurística de splits razão2/3/4/5/6/8/10 com tolerância; ajustes aplicam fator às datas anteriores e não recuperam corporate action oficial.'),
('replay','src/predictor_core/measurement/replay.py','PastView','Iteração com prefixo passado e ordem temporal opcional; available_at pré-validado; objetos de eventos continuam referências compartilhadas.'),
('métricas','src/predictor_core/measurement/metrics.py','brier','Brier/log-loss/RPS/calibração/Diebold-Mariano; as entradas continuam exigindo premissas estatísticas do chamador.'),
('estatística','src/predictor_core/measurement/stats.py','sharpe','Sharpe, Sortino, drawdown, PSR e correlações; não substituem avaliação econômica prospectiva.'),
('bootstrap','src/predictor_core/measurement/bootstrap.py','bootstrap_ci','Reamostragem iid, moving, stationary e cluster; estatísticas não finitas são filtradas e a cobertura é condicional às réplicas válidas.'),
('registro V1','src/predictor_core/measurement/trials.py','TrialRegistry','Registro JSON com trava PID, atualização atômica, histórico superseded e power attestation; bypass explícito power_attestation=False.'),
('registro V2','src/predictor_core/contracts/trial_v2.py','TrialRegistryV2','Registro prospectivo com seleção e proveniência exigidas; read/append/replace não tem a trava do V1.'),
('coleção','src/predictor_core/data/collection.py','CollectionArchive','Histórico JSONL com ciclo de coleta; proíbe converter coleta automaticamente em trial científico.'),
('kernel','src/predictor_core/kernel/jsonl_store.py','JsonlStore','SQLite/WAL/migrações e JSONL/fsync; funções só produzem efeitos quando chamadas.'),
('SQLite','src/predictor_core/kernel/infra.py','connect','Abre SQLite com WAL,busy_timeout,foreign_keys; run_migrations rastreia nomes aplicados em _migrations.'),
('meta','src/predictor_core/kernel/meta.py','validate','Fingerprints de arquivo/parametrização e gate StaleModelError; não garante adequação científica do modelo.'),
('prequential','src/predictor_core/testing/prequential.py','PrequentialEvaluator','Orquestra callbacks train/predict em progressão temporal; algoritmo/modelo é injetado pelo consumidor.'),
('rede','src/predictor_core/kernel/net.py','download_file','Downloads temporários/retry/replace; HTTPX e curl-cffi opcionais; endpoints pertencem ao chamador.'),
('harness','src/predictor_core/testing/harness.py','attest_pipeline_power','Callbacks sintéticos de edge e noise produzem atestado temporal; não confirma lucro ou capital.')],
'areas':{
'A':'Contratos, medição e utilidades sustentam a responsabilidade compartilhada declarada. Não foi encontrado modelo treinado ou autorização de capital nos módulos próprios src/predictor_core integralmente examinados.',
'B':'Pacote src/predictor_core com scientific/data/measurement/stats/kernel/net/infra/collection/testing e fachadas de compatibilidade. Sem project.scripts no manifest observado; scripts de auditoria e verificação de wheel são entradas auxiliares.',
'C':'Python >=3.13, dependências raiz vazias; extras http/httpx e scraping/curl-cffi, dev/test/arquitetura. uv.lock foi parseado integralmente; identidades em dependency-identities.json. Python 3.12 inicial fica fora do suporte declarado; leaf smoke posterior usa 3.13.14.',
'D':'Chamadas de biblioteca recebem objetos/dados/callbacks e retornam contratos, métricas ou registros. Download grava destino do chamador; bancos, trials, eventos e arquivo de coleta persistem quando APIs são invocadas. Erros de validação não promovem estado automaticamente.',
'E':'Parâmetros de timestamps, cutoff, sementes, blocos, SLA e recursos nos contratos; PREDICTOR_EVENTS_PATH seleciona destino de eventos; endpoints/headers/segredos por argumentos. require_secrets testa presença/formato, sem autenticar serviço.',
'F':'DatasetFreeze sela metadados/partições SHA256 sem recuperar origem. PredictionPoint congela estruturas comuns recursivamente; tipos customizados podem continuar mutáveis. Trial V1 JSON histórico, V2 JSON prospectivo, coleção/eventos JSONL, SQLite migrações. Nenhum banco original foi aberto.',
'G':'Métricas probabilísticas, DM com correção HLN, PSR e bootstrap estão implementados. Não há treinamento inferido pelo nome predictor. Premissas de distribuição, alinhamento de séries, causalidade econômica e seleção permanecem externas.',
'H':'Replay valida ordem e disponibilidade, fornece PastView ao handler e reúne ledger. V1 valida trial, adquire lock, verifica atestado quando exigido, preserva superseded e substitui JSON. V2 valida contrato, rejeita id repetido e substitui JSON; precisa controle externo para concorrência.',
'I':'test-assertions.json cataloga testes por função/símbolo, incluindo contratos, métricas golden/sintéticas, travas, provenance e harness. Não executamos pytest completo. Smoke inicial falhou no import por metadados ausentes; três testes de leaf em 3.13 passaram; não são validação da instalação ou ciência real.',
'J':'CI declara Python3.13/3.14 experimental, uv frozen, lint/pyright/import-linter/coverage80, builds e wheel instalada isoladamente. Script sync_core é auditoria de cópias e não foi executado. Execuções atuais do Actions pertencem ao bloco remoto consolidado.',
'K':'README3.2.1 concorda com biblioteca compartilhada e separação ciência/coleta. Documento de migração impresso por sync_core.py ainda cita2.3.0: texto de compatibilidade histórico, não versão atual. Anexo A cita3.2.2; o HEAD local3.2.1 é uma época diferente.',
'L':'Fonte local identificada pela baseline; clone independente no mesmo HEAD. Não houve wheel instalada deste checkout nem serviço ativo validado. Import inicial com fonte sem metadata falhou; smoke leaf evita fachada e não demonstra artefato distribuído.'},
'findings':[
('CORE-01','OD/ET-RUN','Fachada exige distribuição instalada','src/predictor_core/__init__.py','__version__','smoke-run.txt','Import de fonte em cópia sem metadata falhou PackageNotFoundError. Não prova defeito de wheel instalada.'),
('CORE-02','OD','Concorrência V2 não herda trava V1','src/predictor_core/contracts/trial_v2.py','TrialRegistryV2.register','source-catalog.json','Read/append/replace analisado integralmente; testes existentes não comprovam escritores concorrentes V2.'),
('CORE-03','OD','Replay limita visibilidade mas compartilha eventos','src/predictor_core/measurement/replay.py','PastView','leaf-smoke-run-313.txt','Handler só recebe prefixo; referências mutáveis e ambiente externo não são sandboxados.'),
('CORE-04','OD','Bypass explícito do atestado V1','src/predictor_core/measurement/trials.py','register_trial','source-catalog.json','power_attestation=False é caminho de API; consumidores devem decidir e auditar política.'),
('CORE-05','DD/OD','Versão do Anexo difere desta fonte','pyproject.toml','project.version','baseline.json','3.2.1 local versus3.2.2 no Anexo; conclusão restrita ao checkout.')],
'integrations':[
('consumidor Python','core','import/chamada síncrona','src/predictor_core/__init__.py','contratos, dados, métricas','opcional conforme consumidor','sem autenticação própria; callbacks/providers do consumidor','erros tipados de validação','OD/ET-SRC; leaf ET-RUN'),
('core download','HTTP externo','urllib/HTTPX/curl-cffi','src/predictor_core/kernel/net.py','bytes para arquivo destino','rede opcional','headers/URL injetados pelo chamador','retry transitório e arquivo temporário','OD/ET-SRC; rede NV'),
('core registro','filesystem/SQLite','leitura e gravação local','src/predictor_core/kernel/jsonl_store.py','JSONL, JSON trials, SQLite','por API','permissões do processo; sem grants de capital','fsync/replace; lock V1; V2 sem lock','OD/ET-SRC; banco real NV')],
'flow':'flowchart LR\n Consumer[Chamador] --> Contracts[Contrato e timestamps]\n Contracts --> Replay[Replay e PastView]\n Replay --> Handler[Handler do consumidor]\n Handler --> Metrics[Metricas e bootstrap]\n Metrics --> Trials[TrialRegistry V1 ou V2]\n Trials --> JSON[(JSON de trials)]\n Consumer --> Collection[CollectionArchive]\n Collection --> JSONL[(JSONL de coleta)]\n',
'sequence':'sequenceDiagram\n participant C as Consumidor\n participant R as Replay\n participant H as Handler\n participant T as Registro\n C->>R: eventos, key, available_at\n R->>R: validar ordem e disponibilidade\n loop cada evento\n R->>H: PastView com prefixo\n H-->>R: resultado opcional\n end\n R-->>C: ledger\n C->>T: trial e metadados\n T->>T: validar contrato e politica V1/V2\n T-->>C: registro persistido ou erro\n',
'state':'stateDiagram-v2\n COLLECTION_ONLY --> HYPOTHESIS_REGISTERED\n HYPOTHESIS_REGISTERED --> DATASET_FROZEN\n DATASET_FROZEN --> PENDING_SAMPLE\n PENDING_SAMPLE --> SHADOW\n SHADOW --> GO\n SHADOW --> NO_GO\n GO --> CLOSED_BY_HUMAN_DECISION\n NO_GO --> CLOSED_BY_HUMAN_DECISION\n'},
'predictor-ops':{
'root':r'C:\PREDICTORS\predictor-ops','version':'4.2.1',
'purpose':'Supervisor local de subprocessos, locks, heartbeat, proveniência e restrições operacionais. Estados científicos são transportados como metadados; o runner não calcula edge.',
'components':[
('CLI','src/predictor_ops/cli.py','main','validate, provenance e run; JSON de erro sanitizado e sinais de shutdown.'),
('configuração','src/predictor_ops/config.py','HttpJobConfigSource','JSON local ou HTTPS por interface de biblioteca; CLI seleciona arquivo.'),
('modelos','src/predictor_ops/models.py','JobConfig','Pydantic; schemas jobs1/2/3, chave econômica e limites/snapshot.'),
('runner','src/predictor_ops/runner.py','run_job','Trava, idempotência econômica, risco, subprocesso, captura limitada, heartbeat e persistência final.'),
('processos','src/predictor_ops/processes.py','WindowsJob','Windows JobObject/suspensão inicial; POSIX grupo de processos; limpeza/timeout.'),
('runtime','src/predictor_ops/runtime.py','LocalBackend','O_EXCL com guard de SO e posse run_id; JSON atômico/fsync e JSONL com trava.'),
('proveniência','src/predictor_ops/provenance.py','collect_provenance','Git limpo ou wheel RECORD sha256; strict rejeita identidade não verificada.'),
('redação','src/predictor_ops/redaction.py','redact_text','Sanitização de chaves/flags/headers/valores; colhe valores sensíveis longos.'),
('risco','src/predictor_ops/operations.py','retry_action','Kill switch fail-closed e conselho de retry/reconciliação; não automatiza ordens.'),
('health Windows','src/predictor_ops/windows.py','inspect_scheduled_task','Consulta PowerShell do agendador; não registra tarefas.'),
('health','src/predictor_ops/health.py','assess','Combina heartbeat terminal/frescura e status agendador opcional.'),
('observabilidade','src/predictor_ops/observability.py','configure_otel','JSON logging; OTEL opcional configurado por chamador.')],
'areas':{
'A':'Supervisor operacional genérico e reutilizável; resultado SUCCEEDED é sucesso de subprocesso, não GO científico. Permissão de capital é dado explícito do config, não autorização autenticada em uma corretora.',
'B':'Pacote src/predictor_ops, CLI predictor-ops e __main__, scripts validate_installed/published/consumers, testes_v2 e integração POSIX/Windows. Dockerfile declara ambiente de container; testes de Windows criam tarefas e por isso não foram executados.',
'C':'Python>=3.13; pydantic e pydantic-settings declarados. uv.lock parseado integralmente em dependency-identities.json. Runtime disponível3.12 tem Pydantic mas não pytest;3.13 não tem Pydantic. Smoke3.12 é exploratório fora do suporte, sem instalação de dependências.',
'D':'CLI validate lê JSON; provenance verifica identidade; run configura e aciona subprocesso. FileJobConfigSource e HttpJobConfigSource implementados. Runner escreve heartbeat/run/events, captura streams e encerra árvore em timeout, shutdown ou perda da trava.',
'E':'JobConfig: argv/cwd/env,timeout3600,heartbeat30,output10MB,expected_artifacts,provenance_mode,job_type/economic_key. Runtime local default home/.local/state/predictor-ops,TTL86400. Configuração de capital exige todos limites e snapshot atual confiável explícito.',
'F':'runtime por job: lock,heartbeat.json,runs/<run_id>.json,events.jsonl e economic record. Chave econômica inclui cinco dimensões/UTC com separador reservado e SHA256. Claim IN_PROGRESS anterior ao child; ambiguidade em execução de capital é preservada para reconciliação. Expected_artifacts apenas verifica existência.',
'G':'Regras de kill switch bloqueiam dado ausente, velho/futuro, fonte não confiável, saúde falsa ou limiar atingido. retry_action retorna recomendação por estado de ordem; runner não faz reexecução automática. Exit0SUCCEEDED,2PARTIAL e restantes FAILED são mapeamentos operacionais.',
'H':'Validar config → adquirir lock → verificar idempotência/risco → coletar proveniência → registrar início → spawn possuído → heartbeat/captura limitada → terminar/limpar → persistir terminal/release. Falhas pré-spawn3,reader74,lockloss75,timeout124 e shutdown130 têm caminhos próprios.',
'I':'Testes existentes cobrem travas multiprocessos, árvore real, memory bound, redaction adversarial, wheel adulterada e scheduler Windows. ET-SRC não é execução. Três smokes stdlib do runtime/advisory em3.12 passaram; runner com deps/CLI/wheel/Windows não foi validado nesta investigação.',
'J':'CI declara Linux/Windows3.13 e Linux3.14,lint,typing,coverage80,security,pip-audit,build/wheel fora da fonte e container. Docker Python3.14Alpine digest/nonroot. Módulo windows consulta tarefas existentes; suite windows_integration cria/remove tarefa temporária se executada.',
'K':'README4.2.1 concorda com supervisor e declara histórico de implantação com agendamentos desativados. Não tratamos esse relato como daemon atual. Anexo cita4.2.2rc2; fonte local4.2.1 e raiz qualificação4.2.2rc1 são épocas distintas.',
'L':'Checkout4.2.1 e cópia independente identificados. Nenhuma instalação atual4.2.1,container ativo,serviço/agendamento ou execução econômica foi confirmado. Verificação remota e alternativa4.2.2rc1 em blocos separados.'},
'findings':[
('OPS-01','OD','Artefato esperado é existência apenas','src/predictor_ops/runner.py','run_job','source-catalog.json','Caminho existente pode ser antigo; este gate não valida hash, conteúdo ou origem do artefato.'),
('OPS-02','OD','Chave econômica impede reexecutar ambiguidade','src/predictor_ops/runner.py','run_job','source-catalog.json','Capitalpermission conserva registro prévio e requires_reconciliation. Não executa reconciliação externa automaticamente.'),
('OPS-03','OD/ET-SRC','Travas e ownership de processos têm mecanismos reais','src/predictor_ops/runtime.py','LocalBackend','test-assertions.json','Guard de SO/O_EXCL/runid e JobObject/grupo POSIX; testes adversariais existem, não foram executados nesta rodada.'),
('OPS-04','ET-RUN/NV','Smoke está fora do runtime declarado','pyproject.toml','requires-python','smoke-run.txt','3 testes passaram em3.12;>=3.13 exige dependências não disponíveis e não foi substituído por falsa equivalência.'),
('OPS-05','OD','Permissão de capital vem do config','src/predictor_ops/models.py','JobConfig','source-catalog.json','Kill switch valida declarações locais; autorização de pessoa/corretora e fonte de risco real não comprovadas.')],
'integrations':[
('CLI/chamador','subprocesso arbitrário','Popen sincronizado','src/predictor_ops/runner.py','argv/env/output/exit/state','central','permissão SO herdada; config de capital+risco','timeout/shutdown/perda lock encerra árvore','OD/ET-SRC; child atual NV'),
('runner','filesystem runtime','local lock/JSON/JSONL','src/predictor_ops/runtime.py','runid/heartbeat/economickey/provenance','obrigatória','permissões SO; run_id de posse','atomic replace/fsync,ambiguidade preservada','OD/ET-SRC; auxiliares ET-RUN3.12'),
('health Windows','Task Scheduler','PowerShell consulta','src/predictor_ops/windows.py','status/action/last_result','opcional Windows','permissão SO; sem credenciais persistidas','fail-closed missing/denied/schema','OD/ET-SRC; scheduler atual NV'),
('HttpJobConfigSource','servidor HTTPS','urlopen','src/predictor_ops/config.py','JobsFile JSON1/2/3','opcional biblioteca','headers injetados;HTTPS obrigatório','timeout/validação Pydantic','OD; serviço NV'),
('observabilidade','OTEL exporter','SDK opcional','src/predictor_ops/observability.py','spans/logs','opcional','endpoint por argumento','dep opcional','OD; uso no runner não encontrado no escopo src integral')],
'flow':'flowchart LR\n CLI[CLI ou biblioteca] --> Config[JobConfig e validacao]\n Config --> Lock[Lock e idempotencia]\n Lock --> Risk[Kill switch]\n Risk --> Provenance[Proveniencia]\n Provenance --> Child[Subprocesso possuido]\n Child --> Capture[Heartbeat e captura limitada]\n Capture --> Final[Persistencia terminal e release]\n Final --> Runtime[(JSON JSONL runtime)]\n',
'sequence':'sequenceDiagram\n participant C as CLI\n participant R as Runner\n participant B as LocalBackend\n participant P as Child\n C->>R: JobConfig\n R->>B: acquire e economic claim\n alt bloqueio ou registro ambiguo\n R-->>C: SKIPPED ou CONFIGURATION_ERROR\n else permitido\n R->>R: risco e proveniencia\n R->>P: spawn com ownership\n loop enquanto ativo\n R->>B: refresh e heartbeat\n P-->>R: output limitado\n end\n R->>P: cleanup da arvore\n R->>B: persistir terminal e liberar lock\n R-->>C: RunResult\n end\n',
'state':'stateDiagram-v2\n [*] --> WAITING\n WAITING --> RUNNING\n WAITING --> SKIPPED\n WAITING --> CONFIGURATION_ERROR\n RUNNING --> SUCCEEDED\n RUNNING --> PARTIAL\n RUNNING --> FAILED\n RUNNING --> CONFIGURATION_ERROR\n'},
'ecosystem-predictor':{
'root':r'C:\CAIN\contrato','version':'0.2.0',
'purpose':'Registro opcional de plugins e diagnóstico nativo, inventário/compatibilidade declarativos e três contratos de pesquisa publicados separadamente: snapshot,bundle,protocol. Não é por si um transportador de jobs ou uma promoção econômica.',
'components':[
('registro','src/ecosystem/registry/__init__.py','Registry','Descobre entry points predictor.plugins; duplicatas antes de load; diagnóstico separado por domínio e fail-closed.'),
('contrato plugin','src/ecosystem/contracts/v1.py','PluginV1','Protocol health/capabilities e tipos request/response; não implementa handler de inferência.'),
('diagnóstico','src/ecosystem/contracts/diagnostics.py','NativeCapabilities','Estados nativos separados; capital_authorized_by_diagnostic=False; não converte nativo em enum legado.'),
('snapshot','packages/research-snapshot/src/research_snapshot/publication.py','publish','JSON canon/seal, identidade origin4partes,evidence hash/offset; hardlink sem sobrescrever e idempotência por bytes.'),
('bundle','packages/research-bundle/src/research_bundle/__init__.py','validate','Manifest com entidades,evidências,relações,artefatos; limites,hashes e referência local consistente.'),
('filesystem','packages/research-bundle/src/research_bundle/files.py','safe_open','Leitura descriptor/handle sem symlinks/reparse; tamanho/hash/stat; escrita/durabilidade conforme SO.'),
('exportador','packages/research-bundle/src/research_bundle/export.py','Builder','Admissão explícita de fontes,tamanhoUTF8/secret heuristics,trackedcommit,exporterfingerprint e publication fora da raiz produtora.'),
('protocolo','packages/research-protocol/src/research_protocol/__init__.py','verify_task','Task/Result/EnvelopeV1 NFC sem floats,HMAC; cálculo de net/cutoff/estados restritos e resolver externo de chave.'),
('chaves','packages/research-protocol/src/research_protocol/key_store.py','HmacKeyStore','SQLite metadata/vault separado,ACL,rotação,VERIFY_ONLY grace,revoke,backup/restore; não aberto nos originais.'),
('inventário/drift','scripts/check_ecosystem_drift.py','check_offline','Confronta registros,hashes declarados e validade temporal de attestations; não prova ciência.'),
('integração real','scripts/check_real_plugin_integration.py','main','Valida fontes/wheel precisas e plugins instalados e produz receipt de ambiente; não executado.'),
('saúde externa','ecosystem_health.ps1','wrapper','Chama script fora da raiz e append log C:/CAIN; comentário read-only não garante leitura pura.')],
'areas':{
'A':'API opt-in de plugins e contratos de evidência/pesquisa, preservando nomes e estados dos domínios. diagnóstico declara capitalFalse; estrutura de bundle/protocol não comprova verdade da hipótese nem execução real do consumidor.',
'B':'Root ecosystem0.2.0 mais research-snapshot1.0.2rc1,bundle1.0.1rc1,protocol1.0.3rc1: quatro pyprojects neste checkout. Root sem scripts CLI; scripts de inventário/drift/install/integration e wrapper PowerShell; pacotes de contrato independentes.',
'C':'RootPython>=3.13,<3.15 Pydantic; subpacotes>=3.11 e stdlib exceto bundle depende snapshot exato. Rootuv.lock parseado. Versão runtime literal ecosystem.__version__0.1.0 difere manifest0.2.0. Raízes e artefatos alternativos separados.',
'D':'Registry descobre entrypoints sob demanda e chama health/capabilities. Snapshot/bundle APIs validam/leem/exportam/publicam; protocolo valida/assina/verifica payload; HmacKeyStore cria vault/banco quando instanciado. install_candidate instala consumidores remotos e não foi executado.',
'E':'registry JSON centraliza nomes,commits,wheelURLs/hashes,candidate/harness. Builder exige admitted_sources e expected hashes; limites/tamanhos/vocab e profiles são código. Resolver keys define confiança de publisher/key/scope fora de verify_task. Wrapper externo usa Python3.14 e log de C:/CAIN.',
'F':'Snapshot JSON canonical origin4partes,records/evidence offsets/hash; bundle JSON manifest/artifact files/referential integrity; protocolo task/result/envelope HMAC. Keystore SQLite keys/events e vault hashfilename32bytes,active key unique porpub/scope,backupmanifest. Não há abertura de banco original.',
'G':'Regra sem ML: canonNFC/keys estritas/limites/hash/hardlink,net=gross-costs,estados incompatíveis comfalha/capital,isolamento nativo no diagnóstico,HMACcompare_digest. verify_task não avalia relógio atual: validade operacional da expiração pertence ao chamador.',
'H':'Plugin entrypoint→dedupe/load→health/caps→diagnostic envelope. Fonte admitted→hardened read→evidence/entity/relation→seal→publishbundle. Task canonical→signature→resolver→verifyshape; execução/modelagem é externa. Keystore provision→rotate→graceverify→revoke→backuprestore.',
'I':'Testes src cobrem doubles de plugins,contratos/hashes/paths/races,exportação,assinatura/tamper/revocation/backup e registros pinned. Seis smokes anteriores em3.12/3.13 são separados:3.13 contract3PASS. Actualdrift offline1 comdois attestations crypto expirados em27Sep; pytest completo não executado.',
'J':'CI declara bundle311-314,root313/314experimental,coverage75,securityhistory,gitleaks,SBoM,drift,integrationinstalled and pinnedsourcecrypto/cain. Cain-crypto-integration workflow constrói duas vezes,coteja hashes e roda wheels fora dafonte; receipt só criado após comandos, resultado histórico remoto é bloco próprio.',
'K':'README/CURRENT_STATE dizem sete repositórios/dez packages; código e test_architecture_inventory contam onze com protocol quarto pyproject. ArchitectureImplementation nove é histórico. Registry ALIGNED com attestations vencidas é divergência atual offline. AnexoV2/fivepackages descreve outra época, não esta fonte.',
'L':'Root0.2.0 local; literalversion0.1.0. Fourpyprojects tracked; fullfilesearch delimita ausência local transport/compat. Cópia independente;3.13smoke contratos,sem rootinstalledplugins ou E2E. Registrocompatibilidade é candidato estático, não instalação atual nem último servidor.'},
'findings':[
('ECO-01','OD','Manifest e versão runtime divergem','src/ecosystem/__init__.py','__version__','baseline.json','Literal0.1.0 frente pyproject0.2.0; não é verificação de wheel remota.'),
('ECO-02','OD/DD','Onze pacotes no inventário atual contra dez na narrativa','tests/test_architecture_inventory.py','test','source-catalog.json','Sete raízes registry mais protocol quarto pyproject total11; docs dez e histórico nove têm épocas diferentes.'),
('ECO-03','ET-RUN/OD','Dois atestados crypto vencidos seguem ALIGNED','scripts/check_ecosystem_drift.py','check_offline','drift-offline-run.txt','Comando real offline na cópia3.13 exit1 em30Sep; validade até27Sep. Não é execução científica nova.'),
('ECO-04','OD','Wrapper de saúde não é somente leitura','ecosystem_health.ps1','external invocation','source-catalog.json','Chama C:/CAIN/tools/ecosystem_health.py e acrescenta log externo. Não executado.'),
('ECO-05','OD','Verificação protocol é estrutural e criptográfica','packages/research-protocol/src/research_protocol/__init__.py','verify_task','contract-smoke-run-313.txt','Não executa tarefa nem consulta relógio para expiração; confiança scope depende resolver de caller.'),
('ECO-06','OD/NV','Contrato transport/compat não encontrado nesta raiz','packages','inventory','all-files.txt','Busca arquivo integral tracked/untracked exclui.git/.venv/caches; não generaliza servidor/raiz alternativa.')],
'integrations':[
('Registry','plugins instalados','importlib.metadata entry_points','src/ecosystem/registry/__init__.py','health/capabilities native','opt-in','código plugin executa com permissões processo; sem autenticação rede','load errors isolados;dup fail before load','OD/ET-SRC;instalação atual NV'),
('producer','consumer research','snapshot/bundle JSON filesystem','packages/research-bundle/src/research_bundle/export.py','origin,evidence,entities,artifact hashes,relations','API de exportação','admittedsources/hash;restrictionflags declarativos','boundedread/validation/atomicpublication/conflict','OD/ET-SRC;smoke contrato ET-RUN'),
('CAIN/crypto callers','research-protocol','Task/Result/EnvelopeV1 HMAC','packages/research-protocol/src/research_protocol/__init__.py','payloadSHA,messageID,provenance,states,economics','por consumidor','HMAC>=32bytes e keyresolver escopado pelo caller','strictshape,tamper reject;expiração atual externa','OD/ET-SRC;contrato ET-RUN;E2E NV'),
('HmacKeyStore','vault e SQLite','filesystem e transações','packages/research-protocol/src/research_protocol/key_store.py','keys/events/hashreceipts/backups','opcional suporte HMAC','ACLcurrentSID+SYSTEM ouPOSIX700/600','rotategrace/revoke/compensação/restore','OD/ET-SRC;vault original não aberto'),
('scripts registry','GitHub/checkouts externos','git/API/pip workflows','scripts/check_architecture_manifest.py','manifest/commit/wheelversion/hash/receipt','auditoria ouinstallopt-in','GITHUB_TOKEN opcional só nome','unverifiable2/drift1/declaredwarning','OD;rootconsolidado remoto'),
('ecosystem_health.ps1','CAIN/tools + log','PowerShell python subprocess','ecosystem_health.ps1','health/status e appendlog','externa','permissõesSO','exitcode externo','OD;não executado')],
'flow':'flowchart LR\n Entry[Entry points opcionais] --> Registry[Registry]\n Registry --> Diag[Diagnostico nativo]\n Producer[Fontes admitted] --> Snapshot[Snapshot canon]\n Snapshot --> Bundle[Bundle com artefatos e relacoes]\n Bundle --> Consumer[Consumidor externo]\n Keys[KeyStore HMAC] --> Protocol[Task Result Envelope V1]\n Protocol --> Consumer\n Registries[Registries JSON] --> Checks[Drift e inventario]\n',
'sequence':'sequenceDiagram\n participant P as Produtor\n participant B as Bundle Builder\n participant F as Filesystem\n participant C as Consumidor\n P->>B: fontes admitted com hashes\n B->>F: leitura endurecida e bounded\n B->>B: entidades evidencias relacoes e seal\n B->>F: artefatos e manifest em destino exclusivo\n F-->>B: bytes persistidos ou conflito\n B-->>P: bundle publicado\n C->>F: ler manifest e artefatos\n C->>C: validar contrato e hashes\n Note over C: decisao cientifica e grants externos\n',
'state':'stateDiagram-v2\n [*] --> ACTIVE\n ACTIVE --> VERIFY_ONLY: rotate com grace\n VERIFY_ONLY --> REVOKED: revoke ou fim de grace para resolver\n ACTIVE --> REVOKED: revoke\n REVOKED --> [*]\n',
'er':'erDiagram\n KEY ||--o{ EVENT : auditada\n KEY { string key_id PK\n string publisher\n string scope\n string state\n string secret_ref\n string secret_sha256\n string replaced_by }\n EVENT { int sequence PK\n string event\n string detail_json }\n ENTITY ||--o{ RELATION : endpoint\n EVIDENCE ||--o{ RELATION : endpoint\n ARTIFACT ||--o{ RELATION : endpoint\n'}
}

for p,d in DATA.items():
 base=json.loads(study.read(p,study.ROOT/'evidencias'/p/'baseline.json'))
 hashes=json.loads(study.read(p,study.ROOT/'evidencias'/p/'hashes.json'))
 catalog=json.loads(study.read(p,study.ROOT/'evidencias'/p/'source-catalog.json'))
 def ref(path,symbol=''):
  h=hashes.get(path,'consultar hashes.json para caminho efetivo')
  return f'`{path}`'+(f'::{symbol}' if symbol else '')+f' (SHA256 `{h}`; leitura em REGISTRO.log)'
 components=[{'id':x[0],'path':x[1],'symbol':x[2],'role':x[3],'evidence':'OD/ET-SRC','scope':'fonte local','sha256':hashes.get(x[1]),'limit':'Execução/uso atual apenas quando ET-RUN explícito.'} for x in d['components']]
 findings=[{'id':x[0],'category':x[1],'claim':x[2],'path':x[3],'symbol':x[4],'artifact':f'evidencias/{p}/{x[5]}','limit':x[6],'head':base['head'],'sha256':hashes.get(x[3])} for x in d['findings']]
 integrations=[dict(zip(['origin','destination','mechanism','path','payload','required','permissions_auth','errors','evidence'],x),head=base['head'],scope='observado-apenas-localmente',sha256=hashes.get(x[3]),synchronism='síncrono local salvo subprocesso/heartbeat') for x in d['integrations']]
 for filename,value in [('components.json',components),('findings.json',findings),('integrations.json',integrations)]:study.save(f'evidencias/{p}/{filename}',value)
 coverage=[]
 for row in catalog:
  path=row['path'];python=path.endswith('.py')
  coverage.append({'path':path,'sha256':hashes.get(path),'lines':row['lines'],'mode':'leitura semântica integral' if python else 'leitura integral e parsing estrutural','source_log':'REGISTRO.log; shared_scan/shared_view/shared_range e leituras diretas','execution':'Não executado integralmente; ver artefatos ET-RUN','limit':'AST views retiram docstrings; bytes completos previamente lidos e hashados. uv.lock parse integral, assets repetitivos não explicados individualmente.' if python else 'Manifests/registries/lock lidos; leitura não comprova dependência instalada.'})
 study.save(f'evidencias/{p}/coverage.json',coverage)
 intro=f'# Como funciona: {p}\n\nFonte primária: `{d["root"]}`, HEAD `{base["head"]}`, branch `{base["branch"]}`, versão declarada `{d["version"]}`. `origin/main` local e remoto ficam separados em baseline.json. Este texto descreve essa fonte, não substitui estudo da raiz de qualificação ou do servidor.\n\n{d["purpose"]}\n\nOD=observação direta; DD=declaração; ET-SRC=teste existente; ET-RUN=teste desta investigação; NV=não verificado. Todas as referências abaixo remetem ao hash em evidencias/{p}/hashes.json e ao registro append-only.\n\nCaracterização preliminar salva antes da narrativa do repositório; o Anexo A foi exposto na leitura inicial do pedido, limitação de independência explicitamente registrada em PRELIMINAR_{p}.md. Nenhuma memória prévia foi usada.\n'
 areas='\n'.join(f'## {a}. '+{'A':'Propósito','B':'Estrutura','C':'Ambiente','D':'Interfaces','E':'Configuração','F':'Dados e persistência','G':'Algoritmos e decisões','H':'Fluxos completos','I':'Testes','J':'Operação','K':'Documentação e pendências','L':'Fonte e artefato em uso'}[a]+'\n\n'+text+'\n' for a,text in d['areas'].items())
 table='\n## Componentes centrais\n\n|Componente|Fonte e símbolo|Comportamento e limite|\n|---|---|---|\n'+'\n'.join(f'|{x[0]}|{ref(x[1],x[2])}|{x[3]}|' for x in d['components'])
 fs='\n\n## Achados rastreáveis\n\n'+'\n\n'.join(f'**{x[0]} [{x[1]}] — {x[2]}.** {x[6]} Fonte: {ref(x[3],x[4])}; artefato `evidencias/{p}/{x[5]}`.' for x in d['findings'])
 ints='\n\n## Integrações\n\n|Origem → destino|Mecanismo e fonte|Payload, confiança e erro|Estado|\n|---|---|---|---|\n'+'\n'.join(f'|{x[0]} → {x[1]}|{x[2]}; {ref(x[3])}|{x[4]}; {x[6]}; {x[7]}|{x[8]}|' for x in d['integrations'])
 diagrams='\n\n## Diagramas\n\n'+'\n\n'.join('```mermaid\n'+d[k]+'```' for k in ['flow','sequence','state']+(['er'] if 'er' in d else []))
 limits='\n\n## Cobertura, limites e continuidade\n\nCódigo próprio executável, testes, CI, schemas, manifests e lock selecionados constam em source-catalog.json e coverage.json por módulo. Testes foram lidos, mas a suíte completa não foi executada. Documentação narrativa/histórica é amostrada: README, ARCHITECTURE_IMPLEMENTATION, HANDOFF e documentos materialmente relacionados a conflitos; inventário Git delimita os demais. Caches, terceiros, builds e ambientes não foram qualificados como código próprio. Nenhum treinamento, backtest amplo, API paga, instalação pesada, agendamento ou capital foi acionado.\n\nPróximo bloco: confrontar raízes alternativas separadas, finalizar cadeia de assets/README da wheel e CI remota no estudo consolidado. Nenhum ET-RUN limitado deve ser generalizado para estado científico, lucro, autorização de capital ou funcionamento de instalação real.\n'
 study.save(f'docs/COMO_FUNCIONA_{p}.md',intro+areas+table+fs+ints+diagrams+limits)
 inventory=f'# Inventário: {p}\n\nRaiz `{d["root"]}`; HEAD `{base["head"]}`; versão{d["version"]}. A lista rastreada completa está em evidencias/{p}/tracked-files.txt; hashes de todos arquivos regulares rastreados em hashes.json. Coverage enumera leitura semântica/estrutural; documentação histórica não foi presumida atual.\n\n|Arquivo selecionado|Linhas|SHA256|Classificação|\n|---|---:|---|---|\n'
 inventory+='\n'.join(f'|`{r["path"]}`|{r["lines"]}|`{hashes.get(r["path"],"não rastreado")}`|'+('código/teste próprio' if r['path'].endswith('.py') else 'config/contrato/manifest/lock')+'|' for r in catalog)
 inventory+='\n\nDocumentos e demais rastreados não selecionados para código/config são preservados no inventário Git; leitura narrativa material: README.md,ARCHITECTURE_IMPLEMENTATION.md,HANDOFF.md,mais docs temporais/trial(core),OPERATIONS_CONTRACT(ops),CURRENT_STATE/CHARTER(ecosystem). O texto bruto agregado é material intermediário local e não compõe publicação.\n'
 study.save(f'INVENTARIO_{p}.md',inventory)
 for k in ['flow','sequence','state']+(['er'] if 'er' in d else []):study.save(f'diagramas/{p}_{k}.mmd',d[k])
 study.save(f'evidencias/{p}/CONTINUIDADE.md',f'# Bloco concluído\n\nLeitura semântica e confronto preliminar da fonte local `{base["head"]}` concluídos. Entregáveis COMO_FUNCIONA/INVENTARIO, coverage/components/integrations/findings e diagramas salvos. ET-RUN limitados e falhas preservadas. Falta suplemento da raiz alternativa e consolidação remota realizada pelo agente principal.\n')
 study.log(p,d['root'],'Consolidação semântica por módulo e geração entregáveis A-L',0,f'{len(catalog)} arquivos selecionados;{len(components)} componentes;{len(findings)} achados;{len(integrations)} integrações',limits='Fonte local; testes limitados; narrativa histórica amostrada; Anexo exposto antes prelim',artifacts=f'docs/COMO_FUNCIONA_{p}.md;INVENTARIO_{p}.md;evidencias/{p}/coverage.json')
 print(p,'saved')
