import study,json
texts={
'core-predictor':'''Biblioteca Python predictor_core, pacote predictor-core 3.2.1 >=3.13, dependências runtime obrigatórias vazias e extras HTTP/scraping. A API pública lazy exporta contratos de pontos e observações, aquisição/freezes, replay temporal, métricas probabilísticas e financeiras, bootstrap, registros de tentativas e controles sintéticos. Não se encontrou project.scripts no manifest examinado. Kernel oferece SQLite WAL/migrações, JSONL, logging e downloads opcionais. Replay materializa apenas prefixo na PastView, mas mantém referência aos objetos dos eventos; key/available_at são opcionais. TrialRegistry V1 protege novas tentativas e mudanças de veredito por atestado métrica/fingerprint/versão/validade, lock e tmp+replace; TrialRegistryV2 valida proveniência explícita e rejeita trial_id duplicado, porém usa read-modify-write sem o lock/harness V1. Contratos científicos implementam estados e dataset seal, não demonstram edge em dados reais. Testes presentes e inventariados por AST; nenhum resultado de execução inferido. CI local fixa uv 0.12.1 e exige teste/coverage/import-linter/wheel externo. Fontes: pyproject.toml; src/predictor_core/{contracts,data,kernel,measurement,testing}; .github/workflows/ci.yml.''',
'predictor-ops':'''Pacote Python predictor-ops 4.2.1 >=3.13, Pydantic/pydantic-settings, CLI run/validate/provenance. JobConfig determina command argv, cwd, ambiente, timeout, heartbeat, truncamento de saída e runtime root. Runner adquire lock por identidade econômica (ou id), observa idempotency, kill switch e proveniência, inicia subprocesso e persiste heartbeat/events/idempotency. Windows cria processo suspenso e Job Object antes de resumir; POSIX usa process group. Schema permite EXECUTION somente com capital_permission=true e snapshot de risco completo/atual/limites; isso não fornece broker nem prova autorização humana. Scientific state é string opaca. retry_action é recomendação determinística por OrderState; retry_count é metadado. Backend implementado local, agendamento Windows é adapter somente inspeção de tarefas. Docker e CI declarados. Fonte implementa execução genérica arbitrária autorizada por configuração, não motor econômico de domínio. Testes presentes/AST não equivalem execução. Fontes: pyproject.toml; src/predictor_ops; tests_v2; workflows; Dockerfile.''',
'ecosystem-predictor':'''Distribuição ecosystem-predictor 0.2.0 >=3.13,<3.15 com Pydantic; src/ecosystem.__version__ literal 0.1.0. Contratos PluginV1 e registry descobrem predictor.plugins, carregam health/capabilities e degradam falhas; diagnóstico preserva namespace/status nativo sem traduzir significado nem autorizar capital. Há três subpacotes rastreados: snapshot (ResearchSnapshotV1), bundle (ResearchBundleV1 com perfis local-research/1 e /2) e protocol (ResearchTaskV1/ResearchResultV1/AuthenticatedEnvelopeV1 HMAC). Protocolo local restringe tarefas a crypto/BACKTEST_EXISTING_HYPOTHESIS e parâmetros inteiros limitados; JSON canônico NFC e HMAC >=32 bytes. HmacKeyStore guarda metadata.sqlite e vault de arquivos ACL, suporta rotação/revogação/backup. Bundle representa entidades, evidências, artefatos recebidos/referências e relações; publicação exige fontes admitidas por hash e não altera produtor. Snapshot publica por staging/link e conflito/idempotência. CI inclui plugins reais/released wheels e auditorias de registries. Não se encontrou pacote transporte ou compat/ no inventário rastreado; busca estrutural restante pendente. Não há CLI project.scripts no manifest raiz. Fontes: pyproject.toml; src/ecosystem; packages/*/src; CI; locks. Nenhum serviço central foi executado.'''
}
for p,text in texts.items():
 baseline=json.loads(study.read(p,study.ROOT/'evidencias'/p/'baseline.json'))
 body=f'# Caracterização preliminar — {p}\n\nBase local: `{baseline["path"]}`; HEAD `{baseline["head"]}`.\n\n{text}\n\nCategorias: OD para código/manifests; ET-SRC para testes. Hashs e leituras no REGISTRO.log e evidencias/{p}/hashes.json.\n\nLimitação metodológica: o pedido integral foi exibido incluindo o Anexo A antes deste salvamento. Nenhuma narrativa do repositório foi usada na caracterização acima; a independência absoluta frente ao Anexo A não pode ser afirmada. Confronto documental ainda não realizado.\n'
 study.save(f'PRELIMINAR_{p}.md',body);study.log(p,baseline['path'],'Caracterização preliminar salva antes de narrativas dos repositórios',0,'Fontes executáveis/config/testes; limitação Anexo A explicitada',artifacts=f'PRELIMINAR_{p}.md')
study.save('CONTINUIDADE_SHARED.md','Bloco preliminar salvo: core/ops/ecosystem. Próximo: cobertura remanescente de scripts/testes, confronto documental, testes seguros em cópias independentes, matrizes e diagramas. Nenhuma execução nos originais.')
