import study,json
rows=[
('discovery_h17.py','score_outcome/build_cross_sections/summarize/run',9,'H17 price diagnostic: hashes protocolo fixo e arquivos antes/depois; SQLite mode=ro normaliza quote_factor; universo snapshots2018-2025 até60 emissores dedupeCNPJ/PITfiles. Ordena accruals asc seleciona quintil mínimo20; nextsessionopen e nextmonthopen. Rejeita ausênciaendpoint/identitybreak/fatores conflitantes/unmodelled/overnight>30%. Available-caseIC versus complete-case spread; gates por metades fixas. Outputexclusive JSON com investable_alphaFalse e executableprofitNone.','Retorno é preço sem todos proventos/custos; classificação promising é screen não capital. Constância hash não autentica fonte. Calendário insuficiente pode gerar IndexError; não foi executado.'),
('discovery_reorganizations.py','validate_terms/score/run',10,'Recalcula coortes congeladas com ledger de conversão/entitlements. Validaterms únicos ticker/ISIN/exdate,originsSHAURLs,ratiospositivos e datas. followrecursivo depth20; segmentos validamidentidade,fatores,jumps e successors; rights subscriptions zero semexercise. Stockmarks e cashreceivables teóricos somamterminal,creditdate marcadoverificadoantesexit. Dataset/primarysources/protocolhash comparados before/after;outputexclusive.','Inclui recebíveis NÃO spendable e frações teóricas na marca, não dinheiroexecutável. Não muda seleção/fatores dofirst. Physicalcredit verified é teste da data declarada, não brokercredit verificado nesta investigação.'),
('discovery_value.py','value_feature/observe/period_statistics/summarize/run',11,'H18earnings/capitalproxy,H19equity/capitalproxy. ExactdocumentkeyCNPJ/ref/version,receipt+1dia,PITsecuritydocuments,age<=550d,volume>=1MBRL,ONsingleclassACNOR,cotaçãofiscalpróxima<=10d. Ajusta sharesproxy por splitfactor desdefiscal e usa rawcloseasof; earningsannual330-400d. Quartetofamily×horizon1/3m;min20/topquintil;priceoutcomes. Cenáriomissing selected=-100%,other=+100%;haircuts36/72bp/horizonte;stablehalves/material>=.0042/coverage para priorizarrepair.','Decisão é alocação de pesquisa. investablealphaFalse/executableprofitNone; shares reportadas antigas e ausênciaeventosfull/totreturn mantêm proxy limitado.'),
('discovery_value_repair.py','score/run',11,'Remeasure preço conservando features e seleção congelada. Overnight>30 só aceito se reviewedmove casa exatamente ticker/date/ISIN/previousclose/nextopen/factor; notes explicitam override. Protocolhash e inputhash vinculados before/after. Changedreturns auditados; JSONexclusive.','Reviewedmoves/hash não transformam histórico exposto em holdout. Não há custos/totalreturn; aceite fonte declarada não comprova fonteexterna atual.'),
('document_panel.py','fundamentals_asof/capital_from_viewer',11,'Filtra financialavailable/ref<=asof e seleciona latestref/version; filings conflitantes fora campossourcehash rejeitados. Security metadataoptional newestdoc e tickerissuer ambiguity rejeitada. HTML capital parsescellsIDsCVM,escala unidade/mil única,basisdate presente,classsums/treasurybounds;hashraw;outstanding emitido.','capital_from_viewer marca eligible_for_valuation=False/class-price equivalence/interveningevents restantes. Parser é layoutespecífico, sem webreal executado.'),
('big_winner_v2.py','verify_selection_freeze/momentum_12_1/generate_decision',2,'Modelo frozenidentity BIG_WINNER_V2_MOMENTUM_12_1_BASELINE; freezehashcanonical removeartifacthash. Momentum usa apenas datas<asof,253history,value[-253]→[-22];rankingfinite tiebreakticker/topceil20%;fallbacktickeronlyidentity. Shareadjustments<=asof aplicamem datasanteriores.','UNVALIDATED_PROSPECTIVE_CANDIDATE explícito. generate_decision expande **metadata apóscamposfixos, caller pode sobreporidentidade/status/cutoff; canonicalhash por si não verifica esses significados. Sérieschronological/corporateactionsadequados dependem caller.'),
('buffered_rebalance.py','freeze_rebalance/execute_rebalance',2,'FrozenRebalance holdbookdigest projectedentry deepcopied,signalcrossidentity/date/lot/cashceiling. Integer_targets capital;buffer2.5% suprimedifference de holdingscontinuing. Exec requiresreviewedorderunitsTrue,digestentrymatch,execidentity/datelot,stageddeepcopy;rebalance e clearingcheck beforecommitbookdict.','Result SIMULATED_REBALANCE_NOT_PROFIT_EVIDENCE,incrementalsaletaxesFalse/profitNone. Pendingreceivables incluídos sizingceiling; atual funding é RetailBook. Deepcopy+commit não é transação concorrente crossprocess.'),
('cash_events.py','import_verified_events/require_coverage/total_return_series',2,'CSVcash exige ticker/eventid/ex/pay/value/source;pay>=ex,finitepositive,coveredintervals,uniqueduplicate. Savepoint juntaevent ecoverage rows ourollback. Coverage uniãointervals contínuos; totalreturn exigefullcoverage e calcula units/splits+dividends por exdate nos intervalos e reinveste valor econômico.','Coverage fornecida pelo caller não prova fontes completas. Totalreturn econômica por exdate não simula availability de cash na paymentdate; não generalizar para carteira financável.'),
('economics.py','screen/classify',12,'Screen compounding CAGR,populationstdvol/sharpe/drawdown comruin. Configdeclaredfinite(notbool)capital/minannualprofit/maxDD; falta retornaNAO_DECLARADO. Classifica equivalente histórico capital*CAGR vsmin/DD; esperadofutureprofitNone,forecastNOT_ESTIMATED,capacityNone.','BACKTEST_IN_SAMPLE_NET_OF_MODELED_COSTS; passage mínima explicitamente não deploy/capital. Valores declarados não têm boundspositivos todos; estatísticas nãovalidaminputsfiniteindividual neste módulo.'),
('entry_feasibility.py','entry_case/load_unit_reviews',12,'Entrysignal→integersizing→emptyRetailBook→trade→settlement. Açõesentreasof/entry exigemreviewspecialbonusdifferentclass semremover original/unitsunchanged,known<=entry,hashsourceconfinement. Boundary semreview bloqueia,exceptions retornam BLOCKED. Outputstandard/fractional/unfilled/fundedcash.','SIMULATED_ENTRY_ONLY/profitNone/actualcontinuousturnoverNone; novaentrada não recebebonusright. Históriacontínua não qualificada.'),
('etf_hold.py','validate_quotes/simulate/selic_reference',12,'BOVA11/BRBOVACTF003market010R$factor1,OHLC+volpositive,calendarcoverageexact. Decimalcentcost/tax; buy integerlot,opens ouworstopenclose,costtax15%default,unsettledsalereceivable,settleD+3before2019-05-27/D+2after. EquityyearPnl reconcile,equitymarkedDD/underwater/liquidityparticipation;grossSelicdaily series11 benchmarkrequirescoverage.','Singlehold conditionalprofit beforeunknownexpenses; fullynetexecutablenone/futureprofitnone/eventinventoryFalse/capacitynone. Model nãoauditaETFactions; nomes de regras tributárias são modelo implementado, não opinião jurídica atual.'),
('h20_research.py','verify_sources/signal_diagnostics/entry_diagnostics/run',15,'Protocol/inputrawfixedhash,accountarchivesconfinement+binding,executionmanifest. QuarterlyH20 ARMS selection rank,previousINTENDEDmembershipbuffer comparisons; freshentryemptybookcases capital/costgrid throughentry_case;optionalentryreviewaddendum frozenhash. Exposure sourcegate explicit.','COMPLETE_H20_SIGNAL_AND_FEASIBILITY_DIAGNOSTIC_NOT_RETURN_EVIDENCE; nofreshholdout,plannednames notrealturnover,casesprofitNone,newhistoricalreturneval0. Read source/input current via inspectnotlongrun.'),
('ingest_cotahist.py','download_cotahist/_pick_cotahist_txt/parse_cotahist',15,'Corekernelnetdownload B3annualCOTAHIST ZIP. TXTselectionpreferssingleCOTAHIST named orsingleTXT elseerrorambiguity. Streaminglatin1decode zippedfile→cotahist.load_prices→dbconnection closed.','Networkdownload eDBingestmutáveis; nãoexecutados. Imports barecotahist/db exigem configuração de módulo/entrada adequada; arquivo ZIP nãoextraído globalmente por código.'),
('ingest_rj_universe.py','parse_b3_rj_list_html/save_snapshot/propose_universe_rows',17,'urllib currentB3HTMLURLUserAgenttimeout60;HTMLtablecelltickerregexdedupe. Snapshot16hexhashrowsINSERTORIGNORE commit. Diffobservedsnapshot dates entries/exits;propose firstseen as candidate pendingreview,semalteraruniverso. Emptyparse failsbeforewrite.','Livecurrent list não fornece RJrequesthistoricaldate; firstseen écandidate. DefaultURL genericempresaslistadas; parser extrai tickerdequalquertable, nãoevidencia classificaçãoRJ real. save_snapshot retorna leninput mesmoINSERTIGNORE, não rowcountinserido.'),
('monthly_etf.py','monthly_signals/MonthlyTax/simulate',17,'BOVA11quotescalendarcanonicalexactOHLC/BDI02or14,quantitypositive;10completedmonthSMA longclose>SMA,nextexecsession. Hold/trendarms;reserveallmonthlycostsupfront;lots10;cash onlysettled+taxreserved,feesfixedvariable,worstcloseoption. SellpendingD+2/3,monthlyloss carrytax15%,terminal sale,wealthcent/yearaccounting.','CONDITIONAL_SIMULATION; external event/costcertification. Target flips only triggertrade; rejectednoaffordablebuy still sets previous_target=True so retry waits targetcycle. Terminal sell explicitlastday liquidationscenario,notfreshsignal. Não prova legislação/taxreal correctness.'),
('prospective_big_winner.py','append_decision/verify_chain/append_outcome_observation',19,'SQLiteledger_eventsDECISION/CORRECTION sequentialhashchain,uniquepayload,eventhash,triggersforbidUPDATE/DELETE;outcomes uniqueid/horizonmetricsha andtriggers. Decisionid logicalhashasof/model/config/dataset;duplicatepayload idempotent,differentreject;backfill andsignaldayafterfreeze+nonemptycommit eligibility. Correction pointsoriginalhash;artifacthashimmutable compare existing.','verify_chain recomputa eventhash de payload_hash stored, não recomputa payload_json actualhash. Eligible usa signaldate lexical e truthycommit, semverifiedfreezecommit/schema/awaretime. primary_endpoint_mature=int(horizon==12),nãoelapsedtime12m nem observed_at causalvalidation. Leitura integral mostrou gates sãodeclarações estruturais; estudo nãoexecutou.'),
('report.py','build_markdown/write_report',19,'Summarizeseries uses corestatsSharpe/Sortino/maxDD+equity,nonfiniteformatn/d. TemplateverdictPSR/bootstrapDSR/DD e _BIAS_NOTE H1..H19, avisos históricos/price/proventos; default reports path env/configROOT,filenamehypothesis/run writesoverwrite;emitcoreeventcodeversion metricsfinite.','BIAS_NOTE textos são DD embutida, não provaempírica de direção do viés. Mesmo runid pode sobrescreverMD. Template linha custo proportionalturnover/D+1 é declaração fixa não valida upstream execução específica.')]
hashes=json.loads(study.read('stocks-shared',study.ROOT/'evidencias/stocks-predictor/hashes.json'))
coverage=[];notes=[]
for name,symbol,chunk,note,limit in rows:
 path='stocks_predictor/'+name
 item={'path':path,'symbols':symbol,'aggregate':f'executable-{chunk:02}.txt','category':'OD','scope':'fonte primária stocks local; nenhuma execução','sha256':hashes.get(path),'semantic_note':note,'limitation':limit}
 notes.append(item)
 coverage.append({'path':path,'sha256':hashes.get(path),'mode':'leitura semântica integral do agregado de código executável numerado','artifact':item['aggregate'],'full_test_execution':False,'limit':'Agregado omite docstrings/comentários não executáveis; fontebruta/hashes do agente applications. Não muda cobertura de tests.'})
study.save('evidencias/stocks-predictor/shared-review-notes.json',notes)
study.save('evidencias/stocks-predictor/shared-review-coverage.json',coverage)
study.save('evidencias/stocks-predictor/shared-review.md','# Revisão semântica complementar Stocks\n\n17 módulos lidos integralmente no conteúdo executável numerado; sem execução. Fonte/bytes conforme hashes.json e executable-chunks.json. Testes não revistos aqui.\n\n'+'\n\n'.join(f'## {r["path"]}::{r["symbols"]}\n\n{r["semantic_note"]}\n\nLimites: {r["limitation"]}\n\nSHA256 `{r["sha256"]}`, agregado `{r["aggregate"]}`.' for r in notes))
study.log('stocks-shared',study.ROOT/'evidencias/stocks-predictor','Revisão semântica complementar17módulos blocos02/09/10/11/12parcial/15/17parcial/19parcial',0,'Notas de fluxo,dados,gates,limites e paths+hashs salvos',limits='ET-SRC não revistos; nenhuma execução; agregado remove docstrings',artifacts='stocks-predictor/shared-review-notes.json;stocks-predictor/shared-review-coverage.json;stocks-predictor/shared-review.md')
