import study,json
rows=[
('continuous_research.py','validate_contract/inspect_inputs/execute',6,'H19 frozenprotocol/sourceobservationSHAs; syntheticprotocol bypassscientificidentity onlyexplicitmode. Symmetricstrategy/comparison plans,nextsessionentries,datedsettlement,uniquetickers/taxclasslot,explicitliquidation; exactly matches H19frozenquarterly selections. Manifestconfinement+hash; quotetape standard/fractional date/identity/positive/no duplicates. Evidencecalendar/actions/cashknowledge gate beforecontinuouspairedcapital/costgrid. Failures suppress all completedcaseprofits; countsattempted historical separate synthetic.','Blockedmissingevcode2,error1,fullhistoricalnotproofedge0; profitNone top-level. CLI write_text overwritesoutput; sourcechecks metadata notauthentication/completeeconomicproof.'),
('h20_checked.py','verify_evidence/run_checked',14,'Frozenmanifest/gate/code/observationhash fixed; externallylocatedcompare_h20.pyimportexecutedaftercodehashcheck. Runresultserialized exacthash expected, evidencebeforeafter. Outputexclusivexb,claim reproducedonlyifexact.','Paths root/work siblingrepo/data outsideproject. Historicalreproduce does notfreshreturnevaluation,profitNone. NOT executed; code module externalwrites unqualified by this wrapper alone.'),
('h20_continuous.py','H20Policy/make_plans/historical_readiness',14,'ActualRetailBookincumbents tiebreakrank/ISIN causalavailability withrankedcommonuniverse; callsselect_members/freeze_rebalance buffer. makeplans rejectinternalfeaturegap,allowinitialomissions,allarms sameeligibleIDs,explicitterminal. Readinessverifysources/signals/manifests,unionconservativeheldcashintervals andattestationbindsignals/manifest/intervalhash,reviewer/date/sourcefilesconfined/hash.','historical_readiness never callsrun_h20_book: statussourcecheckspass/nohistoricalreturn,profitNone; engineactualposition separateAPI available. Sourceattestation not authenticated revieweridentity; no capital.'),
('paper.py','record_forward/settle_executions/settle_exits',18,'Forwarddate requires todayUTC,DBmaxprice<=asof; selectuniverse→adjust→signals→quintile→decisionsINSERTIGNOREfrozen. legacyentry bypassesforwarddate/contextguard. Settle entries nextopen COALESCE andexits nextmonthend+nextopen modeledroundtripfees/slippage,holdingdays;commitDB. Main only prints legacyinactive withoutbank/cron.','Library remainsmutating andlegacybypass available; runmaininactivity notproof no callers. Countlenranked versusINSERTIGNORE actualwrites; settling changesdecisions exceptCOALESCE fields. Priceperunitnot fundedcash/tax/dividendportfolio.'),
('profit_validation.py','entitlement_book/audit_trials/summarize_audit_periods',18,'Independentmarkedentitlementconversionbook accumulatesgrosscash/successors/splitunits withidentitycollisionguards andmodeopencloseworst. Auditsfrozenselectionmin20quintileCNPJunique/causal,agreesdiagnosticreturns/spread tolerance1e-10. Contiguousperiods requiredcompound; stationarybootstrapstressedspread72bp,block12/horizon,n10000seed20260907;issuerattribution.','Unadjustedadaptivesearch,syntheticcompounding assumesmarks fundnextperiod,endpointDD only; executableprofitFalse. Cashpaymentdate/physicaldelivery not enforced in entitlementmark,not RetailBook.'),
('retail_cash.py','Holding/RetailBook/ordinary_month_tax/execution_readiness',20,'Decimalfinitedatecanonical/integerunits; distinct standard/fractionalprices lot; positiondelivery lockscredit/tradable andsaleavailablebyselltlement. Bookadvance checksdayflows deficits; fundable checksallpendingcash+reserve (rightsnotspendableuntilavailable); entitlements dedupebeforeexdaytrades/ISIN andex<=payment<available. Order nointradayreversal,buysunfilled ifnotfundable,salesbasisproportional,settlementpending. Rebala deepcopystages,sellfirstthenbuy,decrementsharesfundable. Conversion explicitcompletebasisallocation/intunits/no merge. Monthlytax model separatesreviewedcorporatedisposals,equitygross exemptiondefault20000 vsBDR,loss carry15%; daytrades reject. Readiness checkscoverage/fields/review/chronology/quote/action/taxattests.','Taxnumbers são modelo source, não validaçãojurídica atual. Gate provenance declararreview/sources notlivebroker. Two-phase deepcopy local não crossprocesstransação. No full sourcecertification throughenginealone.'),
('rj_coda.py','impute_zeros/clr_matrix',20,'Rectangularmatrix;None/zero imputed delta*.minpositive percolumn default.5 withmask. No-positivecolumns dropped;clr requiresstrictpositive thenlogmean centering; failedrows markedNone,maskcolremapped.','Imputation is localstatisticaltransform notrecoveredprimarydata; negativevalueskeep thenfailCLR. No runtime validationdeltabounds/numericfinite allobservations; no predictivevalidation.'),
('rj_episodes.py','point_in_time_candidates/classify_episode',20,'Localtrough fullwindow retrospective helper versusPIT rollingcandidate40dayssinceRJ requests,chosenfirstprimary/separatedsecondary. RallyfirsthitthresholdwithinNdays;classifyserieslastdate<=asoftodayassert,invalidnonpositive→invaliddata,completewindow/nohit→no_rally,censoredshortwindow.','Retrospectivelocaltrough helper is notcausalcandidate; code distinguishes both. asof cutoff presumes sortedseries,backwardlookbackvalidation notbroad. Outcomes descriptive nofundedprofit.'),
('source_closure.py','audit/source_counts',24,'Frozenbaseline/sourceprotocol/signals hash;revisedmanifest mayonlyaltercash/corporate/evidence/tax,plans/quotesimmutable,taxrules unchangedexceptlocalrefs. Primarycataloghashbinding andderivedlocalSHAcannotrelabelprimary. Recursive sourcerefbound,duplicatecoalesce originalrows,entitlementparentchildexactset/noduplicates/identity/amount/crosspaymentrounding1e-9. Removedactiongaps onlyspecificactions;quotesloaded andconservativeH20intervalunion; beforeafterchecks.','AlwaysappendsH20_CONTINUOUS_SOURCE_ATTESTATION_MISSING andreturnsBLOCKED/code2/noevaluation/profitNone. Auditing repairs não qualifica executablehistory. Some source_kind defaultUNCLASSIFIED intentional.'),
('source_history.py','document_metadata/derive_fca_securities/security_links_asof/derive_reported_capital',24,'ZIPCVMFCA/FRE metadata ID,CNPJ14,ref,version>=1,receipt→availability;exactidentitymatch sourceCSV. Securityticksregex/issuesunsupported/tradinginterval;rawhash+row;selectlatestref/version/availability<=asof andactiveinterval. CapitalEmitido onlyfiniteintegralshares/classsum validate;missingrecordissues;reportedtotal orONPN classification.','Capitalbasis_dateNone/eligible_for_valuationFalse. Declaredsharequantity não vincula securityclasseconomic equivalence. Sourcehash provenance notsourceexternalliveness.'),
('stock_events.py','import_bonus_events/bonus_events',24,'JSONbonuspayloadSHA,canonicalex/creditdatecredit>=ex,finitepositiveratio,ticker/eventsource,duplicateidentityreject;append_rows stock_bonus_events;queryex<=end orderedex/credit/id.','No classconversion/cash/fractions suppliedby thisimportalone. Code supportsDBmutation,notexecuted;append_rows semantics belongcvm_pit.'),
('value_profitability.py','prepare_snapshot/rank_snapshot/select_members',25,'H20threeARMS commoneligiblecoverage. Exactaccountingkeydocument/ref/version/sourcehash/PITavailabilityreceipt+1day,<=550d,ownerearnings/equity explicit2equityrows arithmetic. Annualearnings330-400d/equity>0,preparedH18/H19 mustmatch exactnumerators tolerance;valueequity/capprofitabilityearnings/equity. Descendingmidranks/ticker tie;valueonly versusmeanvalue+profitrank. Min20 topfloor20%,retainactualincumbentmatchingISINwithinceil30% thenfillbest.','SIGNAL_SELECTION_ONLY; retention signalmodel não prova savedturnover/returns. Negativeearningseligible;sectorsnotneutralized;proxycapital fromupstream remainsstale. Noauth sourcetruth.'),
]
hashes=json.loads(study.read('stocks-shared',study.ROOT/'evidencias/stocks-predictor/hashes.json'))
notes=[];coverage=[]
for name,sym,chunk,note,limit in rows:
 p='stocks_predictor/'+name
 r={'path':p,'symbols':sym,'aggregate':f'executable-{chunk:02}.txt','category':'OD','scope':'fonte primária stocks local; nenhuma execução','sha256':hashes.get(p),'semantic_note':note,'limitation':limit}
 notes.append(r);coverage.append({'path':p,'sha256':hashes.get(p),'mode':'leitura semântica integral do agregado executável numerado','artifact':r['aggregate'],'full_test_execution':False,'limit':'Não redefine cobertura de tests;docstrings removidas agregados.'})
study.save('evidencias/stocks-predictor/shared-review2-notes.json',notes)
study.save('evidencias/stocks-predictor/shared-review2-coverage.json',coverage)
study.save('evidencias/stocks-predictor/shared-review2.md','# Revisão complementar2 Stocks\n\n12 módulos próprios integralmente lidos no agregado executável numerado; nenhumaexecução.\n\n'+'\n\n'.join(f'## {r["path"]}::{r["symbols"]}\n\n{r["semantic_note"]}\n\nLimites:{r["limitation"]}\n\nSHA256`{r["sha256"]}`;{r["aggregate"]}.' for r in notes))
study.log('stocks-shared',study.ROOT/'evidencias/stocks-predictor','Leitura semântica12módulos restantes06/14/18/20/24/25',0,'Notas gates/persistencia/algoritmos/limites salvos',limits='Nenhumaexecução;testes não revisados nesta parcela',artifacts='stocks-predictor/shared-review2-notes.json;stocks-predictor/shared-review2-coverage.json;stocks-predictor/shared-review2.md')
