"""integration-crypto, contract-revalidation, parte (d) de C24.3 (DOMAIN_CONTRACTS_PRESERVED), no runtime suportado.

O vetor real da Etapa A do cripto (qualification/crypto/scripts/real_env.py: `crypto:REQ-REAL-E2E-001`, dataset
real-in-sample) é embrulhado numa ResearchTaskV2 (protocolo congelado, venv do CAIN) e entregue pelo consumidor do
transporte ao adapter. Confere:
  * o pedido que o adapter gera tem o mesmo hash canônico sem client_ref do vetor da Etapa A (o request_content_hash
    que o domínio grava no resultado == o sha256 canônico do vetor);
  * o client_ref volta igual (outcome e resultado V2);
  * o payload de domínio no ResultV2 é byte-idêntico ao do adapter_api (== `cripto-research show`, processo novo).
Uso (com o env.sh do runtime_env.sh): python contract_d.py <qualification/integration-crypto> <work> <out>
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from harness import Harness

BUILD = r'''
import json, sys
from pathlib import Path
from research_protocol import v2
from research_transport.spool import Spool
vector = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
task = v2.build_task("crypto", vector, episode_id="crypto:episode-1", proposal_id="cain:CONTRACT-D",
                     created_at="2026-09-27T00:00:00Z")
print(json.dumps({"task_id": task["task_id"], "vector_sha256": v2.request_content_hash(vector),
                  "spool": Spool(sys.argv[2]).put_task("crypto", v2.dumps_task(task))}))
'''
VECTOR = r'''
import importlib.util, json, sys
spec = importlib.util.spec_from_file_location("real_env", sys.argv[1])
module = importlib.util.module_from_spec(spec); spec.loader.exec_module(module)
print(json.dumps(module.request("crypto:REQ-REAL-E2E-001", "real-in-sample")))
'''


def main() -> int:
    mission, work, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    h = Harness(out, work, mission, "contract-revalidation-d")
    real_env = mission.parent / "crypto" / "scripts" / "real_env.py"
    (work / "vector.py").write_text(VECTOR, encoding="utf-8")
    _c, lines, _ = h.run("Stage A vector (real_env.request)", [os.environ["CONSUMER_PY"], "-I", work / "vector.py",
                                                                  real_env])
    vector_path = work / "stage-a-vector.json"
    vector_path.write_text(json.dumps(lines[0]), encoding="utf-8")
    (work / "build.py").write_text(BUILD, encoding="utf-8")
    _c, lines, _ = h.run("wrap the vector in a V2 task", [os.environ["CAIN_PY"], "-I", work / "build.py", vector_path,
                                                          h.spool])
    built = lines[0]
    _c, delivered, _ = h.consumer("consumer")
    h.check("(d) delivered through the adapter_api", delivered and delivered[0].get("status") == "RESULT", got=delivered)
    (path, result), = h.results()
    payload = json.loads(result["result"]["payload_canonical"])
    task = h.task(built["task_id"])
    h.check("(d) request generated by the adapter has the canonical hash of the Stage A vector (without client_ref)",
            payload["provenance"]["request_content_hash"] == built["vector_sha256"] == task["payload_sha256"],
            domain=payload["provenance"]["request_content_hash"], vector=built["vector_sha256"])
    h.check("(d) client_ref returned unchanged", result["client_ref"] == task["payload"]["client_ref"])
    h.provenance(result, task)
    return h.finish({"vector": lines and built})


if __name__ == "__main__":
    raise SystemExit(main())
